-- Seed data applied after `supabase db reset`.
--
-- The Duet word list lives at the bottom of the tinyspy baseline
-- migration (20260615000001_tinyspy.sql) so it ships to
-- hosted projects via `supabase db push`. This file is kept so the
-- Supabase CLI doesn't complain about a missing seed file; add
-- per-env one-off data here if needed.
