// cs-blessed-manifest

/**
 * The vocabulary every game's `labelFor` speaks — the club-page **status
 * line**, the second line of a game row. This file is where the rules live;
 * `npm run report:labels` prints every game's actual output, generated by
 * running the real `labelFor`s.
 *
 * These helpers decide the shape once, so no game has to invent its own word
 * for "in progress" or its own phrasing of "alice won":
 *
 *     OUTCOME (why) · other · facts
 *
 * **The lead is one of four words** — `Playing`, `Won`, `Lost`, `Ended`. It is
 * what survives truncation on a narrow row, so it carries the thing you scan
 * for, and a game does not get a flavor word of its own.
 *
 * **Exactly two devices, and no third.** Parentheses carry a reason; `·`
 * separates facts. Nothing else separates anything — there is no second
 * separator to reach for.
 *
 * Four conventions, each easy to get subtly wrong:
 *
 *   - A **reason belongs on a loss or an end, not on a win.** `Won by alice
 *     (out of time)` fights itself; how a win arrived rarely matters.
 *   - **A winner is `Won by alice`**, no parentheses — "by alice" reads as
 *     English, and parentheses are for the why.
 *   - **A status line may only say what every player already sees.** It's
 *     rendered from `common.games.status`, which is readable by the whole
 *     club, so a compete game's private per-player progress must NOT appear
 *     here — that's why several compete labels are a bare `Playing`.
 *   - **Every `labelFor` is an exhaustive `switch` whose `default` returns the
 *     raw `play_state`.** A state nobody wrote an arm for then renders visibly
 *     wrong, rather than quietly claiming the game is live.
 */

import { DIFFICULTY_LABELS } from '../setup-form/difficulty'

/** The separator between facts. One character, one meaning. */
const SEP = ' · '

/**
 * Join the parts of a status line, dropping the empty ones — so a caller can
 * write the optional facts inline (`count && \`${count} left\``) instead of
 * assembling an array by hand.
 */
export function statusLine(...parts: (string | null | undefined | false)[]): string {
  return parts.filter((p): p is string => Boolean(p)).join(SEP)
}

/**
 * The status line's leading verdict, with an optional parenthesized reason:
 * `Lost` / `Lost (out of time)`. The reason is the *why*, phrased in the
 * game's own noun — "out of guesses", "out of swaps", "4 mistakes" — and it is
 * usually `status.reason` run through the game's own words.
 *
 * NOT `outcome`: that word names the six-value appearance vocabulary
 * (docs/outcomes.md), and none of these four is one of them.
 */
export function verdict(word: 'Playing' | 'Won' | 'Lost' | 'Ended', reason?: string | null): string {
  return reason ? `${word} (${reason})` : word
}

/** `Won by alice` — the winner is extra info about the verdict, so no parens. */
export function wonBy(username: string | null | undefined): string {
  return username ? `Won by ${username}` : 'Won'
}

/**
 * The dictionary band a game was set up with: `dict "Familiar"`.
 *
 * Only for the games whose FEEL changes a lot between bands (waffle, wordle,
 * stackdown) — for spellingbee or boggle the band barely shows, and a constant
 * word on every row would just eat the row's width. Quoted because a bare
 * `dict Familiar` reads like a typo; the band names aren't self-evident.
 *
 * Read off `setup` rather than `status`, unlike everything else a status line
 * says: `common.reset_game` assigns the status blob wholesale, so a key written
 * at create time would not survive a restart.
 */
export function dictLabel(band: number | null | undefined): string | null {
  if (band == null) return null
  const name = DIFFICULTY_LABELS[band - 1]
  return name ? `dict "${name}"` : null
}

/** Read a numeric setup field off the (untyped) listing row. */
export function setupNum(
  setup: Record<string, unknown> | null,
  key: string,
): number | null {
  const v = setup?.[key]
  return typeof v === 'number' ? v : null
}

/** `2/3 found`, `21/50 pts` — a tally, or null when either half is missing. */
export function tally(
  have: number | null | undefined,
  total: number | null | undefined,
  noun: string,
): string | null {
  if (have == null || total == null) return null
  return `${have}/${total} ${noun}`
}

/** `1 mistake` / `2 mistakes` — pluralize a counted noun. */
export function count(n: number | null | undefined, noun: string, plural = `${noun}s`): string | null {
  if (n == null) return null
  return `${n} ${n === 1 ? noun : plural}`
}
