import { describe, expect, it } from 'vitest'
import { buildTrie, createSolver, parseBoard } from './solver'
import { boggleSolverFixture as fixture } from './solver.fixture'

/**
 * Parity test: the TS solver must reproduce, exactly, the output of the original
 * wsboggle C solver (`libwords.c`) — our golden-master oracle. The fixture was
 * generated by `boggle-c-solver/dump_fixture.c` over a compact 2000-word common
 * dictionary and boards at 4×4 / 5×5 / 6×6 that include multiface (Qu/In/Th/Er/He)
 * tiles. Each case carries the C oracle's full-enumeration word count, longest
 * length, and basic-ladder score for that board.
 */

describe('boggle solver — parity vs C oracle (libwords.c)', () => {
  const { solve } = createSolver(buildTrie(fixture.dict))
  const opts = { minWordLength: fixture.minWordLength, ladder: fixture.ladder as 'basic' }

  for (const n of [4, 5, 6]) {
    it(`reproduces the oracle on every ${n}×${n} board`, () => {
      const cases = fixture.cases.filter((c) => c.n === n)
      expect(cases.length).toBeGreaterThan(0)
      const mismatches = cases
        .map((c) => ({ c, r: solve(parseBoard(c.board), opts) }))
        .filter(({ c, r }) => r.count !== c.count || r.longest !== c.longest || r.score !== c.score)
        .map(({ c, r }) => ({
          board: c.board,
          expected: { count: c.count, longest: c.longest, score: c.score },
          got: { count: r.count, longest: r.longest, score: r.score },
        }))
      expect(mismatches).toEqual([])
    })
  }
})

describe('boggle solver — units', () => {
  it('finds each word once, with correct longest + score', () => {
    // 2×2 (all tiles mutually adjacent): C A / T R
    const { solve } = createSolver(buildTrie(['cat', 'car', 'arc', 'tac', 'dog']))
    const r = solve(parseBoard('CATR'))
    expect(r.count).toBe(4) // cat, car, arc, tac (dog isn't traceable here)
    expect(r.longest).toBe(3)
    expect(r.score).toBe(4) // basic ladder: 4 three-letter words × 1
  })

  it('dedups a word reachable by two paths', () => {
    // "eve" traces E0–V1–E2 and E2–V1–E0 — same word, one terminal node.
    const { solve } = createSolver(buildTrie(['eve']))
    const r = solve(parseBoard('EVEX'))
    expect(r.count).toBe(1)
    expect(r.longest).toBe(3)
  })

  it('handles a multiface An (digit 6) tile — not covered by the fixture', () => {
    // cell 0 = "6" → An (a,n); cell 1 = D. "and" = An + D.
    const { solve } = createSolver(buildTrie(['and']))
    const r = solve(parseBoard('6DXX'))
    expect(r.count).toBe(1)
    expect(r.longest).toBe(3)
  })

  it('flat ladder scores 1 per word, and count is ladder-independent', () => {
    const { solve } = createSolver(buildTrie(fixture.dict))
    const c = fixture.cases.find((x) => x.n === 4 && x.count > 0)!
    const r = solve(parseBoard(c.board), { minWordLength: 3, ladder: 'flat' })
    expect(r.score).toBe(r.count)
    expect(r.count).toBe(c.count)
  })

  it('fail-fasts (busted) once maxWords is exceeded', () => {
    const { solve } = createSolver(buildTrie(fixture.dict))
    const c = fixture.cases.find((x) => x.n === 4 && x.count > 5)!
    const r = solve(parseBoard(c.board), { maxWords: 1 })
    expect(r.busted).toBe(true)
  })
})
