#!/usr/bin/env -S npx tsx
/**
 * Generate the bundled scrabble dictionary asset from `common.words`.
 *
 * The scrabble move suggester (the `scrabble-suggest-move` edge function)
 * needs the full legal word set to generate moves against. Same bundling
 * rationale as boggle's (`generate-boggle-wordlist.ts`): ship it with the
 * function rather than query the DB at cold start. Boggle's bundle can't be
 * reused — it ships only `len >= 3` (scrabble needs the 2-letter words for
 * parallel plays), its `clean` flag isn't scrabble's dialect filter, and it
 * has no length cap (see docs/scrabble-ai.md).
 *
 * Output: `supabase/functions/scrabble-suggest-move/wordlist.ts`, exporting a
 * gzip+base64 blob — one line per word, `"<difficulty><word>"`: the
 * difficulty digit (1–6) then the lowercase word. The word set mirrors
 * `play_word`'s legality exactly: `len` 2..15 (board width) and
 * `american OR british` — no crude/slur/slang filter, profanity is legal in
 * scrabble. All bands ship; the function builds ONE difficulty-rated trie and
 * the per-game band check happens at query time (rated terminals — see
 * `src/common/lib/game/trie.ts`).
 *
 * Connection: SUPABASE_DB_URL (defaults to the local stack). Needs psql on PATH
 * and a populated common.words (run `npm run words:import` first).
 *
 * Usage:  npm run scrabble:wordlist
 */

import { execFileSync } from 'node:child_process'
import { gzipSync } from 'node:zlib'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

const DB_URL =
  process.env.SUPABASE_DB_URL ??
  'postgresql://postgres:postgres@127.0.0.1:54322/postgres'

const OUT = resolve(import.meta.dirname, '../functions/scrabble-suggest-move/wordlist.ts')

// Exactly play_word's word universe: 2..15 letters, american OR british.
const QUERY = `
  select difficulty, word
  from common.words
  where len between 2 and 15 and (american or british)
  order by difficulty, word
`

// -t tuples-only, -A unaligned, -F '\t' tab-separated → "difficulty<TAB>word" lines.
const raw = execFileSync('psql', ['-X', '-d', DB_URL, '-tAF', '\t', '-c', QUERY], {
  encoding: 'utf8',
  maxBuffer: 1 << 28, // ~3 MB of rows; default 1 MB would overflow
})

const lines = raw.split('\n').filter(Boolean)
// Each output line: difficulty digit then the word — e.g. "1the" (band 1).
// Words never contain a tab.
const text = lines
  .map((l) => {
    const [d, word] = l.split('\t')
    return d + word
  })
  .join('\n')

const gz = gzipSync(Buffer.from(text, 'utf8'), { level: 9 })
const b64 = gz.toString('base64')

const out = `// GENERATED by supabase/scripts/generate-scrabble-wordlist.ts — do not edit.
// Regenerate: npm run scrabble:wordlist  (reads common.words; run after words:import)
//
// gzip+base64 of the scrabble dictionary: one line per word,
// "<difficulty><word>" (difficulty 1-6, then the lowercase word). All words
// len 2..15, american OR british, all bands — play_word's exact word
// universe. ${lines.length} words. Decoded at edge cold-start into ONE
// difficulty-rated trie (see ./dict.ts); the per-game band check happens at
// query time.
export const WORDLIST_GZ_B64 =
  '${b64}'
`

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, out)
console.log(
  `wrote ${OUT}\n  ${lines.length} words · ${(text.length / 1e6).toFixed(2)} MB raw ·` +
  ` ${(gz.length / 1e6).toFixed(2)} MB gz · ${(b64.length / 1e6).toFixed(2)} MB base64`,
)
