#!/usr/bin/env -S npx tsx
/**
 * Generate the bundled boggle dictionary asset from `common.words`.
 *
 * The boggle board generator (the `boggle-build-board` edge function) needs the
 * REQUIRED word list to solve boards against. We ship it bundled with the
 * function rather than query the DB at cold start (~2× faster cold start, no DB
 * load on every isolate spin-up; the dictionary is stable — see
 * `docs/games/boggle.md` §5). The required band is a per-game pick, so we ship
 * every difficulty band tagged, and the function builds a band-filtered trie at
 * cold start.
 *
 * Output: `supabase/functions/boggle-build-board/wordlist.ts`, exporting a
 * gzip+base64 blob — one line per word, `"<difficulty><clean><word>"`: the
 * difficulty digit (1–6), a clean flag (`1`/`0`), then the lowercase word. The
 * function decodes + groups it by band into two sets.
 *
 * We ship ALL words `len >= 3` (difficulty-only), each TAGGED with whether it's
 * in the clean "required-eligible" set (american, crude = 0, slur = 0, slang =
 * false). The two boggle word sets need different filters:
 *   - REQUIRED (what a board is built + judged against): clean-only.
 *   - LEGAL / bonus (what else a player may find): difficulty-only — crude,
 *     slur, slang and non-american words all count. So the legal set must
 *     include the words the clean filter drops; the flag lets `dict.ts` build a
 *     clean trie AND an all-words trie from the one asset.
 *
 * Connection: SUPABASE_DB_URL (defaults to the local stack). Needs psql on PATH
 * and a populated common.words (run `npm run words:import` first).
 *
 * Usage:  npm run boggle:wordlist
 */

import { execFileSync } from 'node:child_process'
import { gzipSync } from 'node:zlib'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

const DB_URL =
  process.env.SUPABASE_DB_URL ??
  'postgresql://postgres:postgres@127.0.0.1:54322/postgres'

const OUT = resolve(import.meta.dirname, '../functions/boggle-build-board/wordlist.ts')

// ALL words len >= 3, each tagged `clean` (= required-eligible). The legal set
// filters on difficulty ONLY, so crude/slur/slang/non-american words ship too.
const QUERY = `
  select difficulty,
         case when american and crude = 0 and slur = 0 and slang = false then 1 else 0 end as clean,
         word
  from common.words
  where len >= 3
  order by difficulty, word
`

// -t tuples-only, -A unaligned, -F '\t' tab-separated → "difficulty<TAB>clean<TAB>word" lines.
const raw = execFileSync('psql', ['-X', '-d', DB_URL, '-tAF', '\t', '-c', QUERY], {
  encoding: 'utf8',
  maxBuffer: 1 << 28, // ~3 MB of rows; default 1 MB would overflow
})

const lines = raw.split('\n').filter(Boolean)
// Each output line: difficulty digit, clean flag, then the word — e.g. "11the"
// (band 1, clean) or "10arse" (band 1, not clean). Words never contain a tab.
const text = lines
  .map((l) => {
    const [d, clean, word] = l.split('\t')
    return d + clean + word
  })
  .join('\n')

const gz = gzipSync(Buffer.from(text, 'utf8'), { level: 9 })
const b64 = gz.toString('base64')

const out = `// GENERATED by supabase/scripts/generate-boggle-wordlist.ts — do not edit.
// Regenerate: npm run boggle:wordlist  (reads common.words; run after words:import)
//
// gzip+base64 of the boggle dictionary: one line per word,
// "<difficulty><clean><word>" (difficulty 1-6, a clean flag 1/0, then the
// lowercase word). ALL words len>=3, all bands; the clean flag marks the
// required-eligible set (american, crude=0, slur=0, slang=0). ${lines.length}
// words. Decoded and grouped into a clean set + an all set at edge cold-start
// (see ./dict.ts): required trie = clean, legal trie = all.
export const WORDLIST_GZ_B64 =
  '${b64}'
`

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, out)
console.log(
  `wrote ${OUT}\n  ${lines.length} words · ${(text.length / 1e6).toFixed(2)} MB raw ·` +
  ` ${(gz.length / 1e6).toFixed(2)} MB gz · ${(b64.length / 1e6).toFixed(2)} MB base64`,
)
