import { readFileSync, writeFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { games } from './games'
import type { CommonGameListRow } from './common/lib/games'

/**
 * The club-page **status line** every game renders, per play state — generated by
 * RUNNING each manifest's `labelFor` rather than transcribing 13 implementations.
 *
 * Two jobs, one file:
 *
 *   1. **Regenerate** the table in `docs/game-status-labels.md`:
 *          npm run report:labels
 *      Rewrites everything between the GENERATED markers and passes.
 *
 *   2. **Guard** it the rest of the time: rebuild the table in memory and fail if the
 *      committed doc doesn't match. The failure is ONE message ("stale — run …"), not
 *      130 string diffs, so the doc is reviewed as a document instead of as test noise.
 *
 * Why a vitest file and not a `supabase/scripts/*.ts` run through tsx, like the other
 * generators: this one has to import the manifests, which pull in lazy React components
 * and CSS modules. Vitest already resolves both. The `REPORT=1` regenerate flag mirrors
 * `board-geometry.e2e.ts`'s `BASELINE=1`.
 *
 * **When a game gains a play state, add it to CASES.** The matrix is deliberately
 * hand-written: it encodes which states each game can actually reach and which `status`
 * keys its label reads. A generated cross-product would bury the real states in noise
 * (most games echo an "else" branch for states they never see), and silently omitting a
 * new state is exactly the drift this file exists to catch.
 */

const DOC = 'docs/game-status-labels.md'
const BEGIN = '<!-- BEGIN GENERATED status-lines — edit via `npm run report:labels`, not by hand -->'
const END = '<!-- END GENERATED status-lines -->'

const W = { winner_username: 'alice' }

/** A label row: the state, the status blob its label reads, and how to name the case. */
type Case = [state: string, status: Record<string, unknown>, note: string]
/** Cases are split by MODE because a coop manifest never sees `won_compete` and a compete
 *  one never sees coop's `won` — mixing them generates rows for unreachable states, with
 *  whatever the label's `?? 0` fallbacks invent. `shared` is for the mode-less games. */
type Family = {
  playing: Record<string, unknown>
  shared?: Case[]
  coop?: Case[]
  compete?: Case[]
}

/**
 * Per gametype FAMILY (baseGametype): a realistic mid-game status blob, then the terminal
 * cases that family actually reaches, per mode.
 *
 * **The status keys must match what the RPC really writes.** A missing key silently falls
 * back to the label's `?? 0` / `?? 'someone'` and prints a plausible-looking lie — that is
 * not a hypothetical: an early version of this matrix omitted spellingbee's `target_rank`
 * on manual end and "found" a bug that the SQL had already fixed (it re-emits target_rank
 * for exactly this reason; see the comment in spellingbee.end_game). Check the RPC before
 * adding a case.
 */
const CASES: Record<string, Family> = {
  // No siblings — one manifest, one vocabulary.
  codenamesduet: {
    playing: {},
    shared: [
      ['sudden_death', {}, 'sudden death'],
      ['won', {}, 'won'],
      ['lost_assassin', {}, 'assassin'],
      ['lost_clock', {}, 'out of turns'],
      ['lost_timeout', {}, 'timeout'],
      ['ended', {}, 'manual end'],
    ],
  },
  psychicnum: {
    playing: { guesses_remaining: 5 },
    shared: [['ended', { outcome: 'manual' }, 'manual end']],
    coop: [['won', W, 'found it'], ['lost', {}, 'out of guesses / time']],
    compete: [['won_compete', W, 'won the race'], ['lost', {}, 'out of guesses / time']],
  },
  connections: {
    playing: { matched_count: 2, mistake_count: 1 },
    shared: [['ended', { outcome: 'manual', matched_count: 2 }, 'manual end']],
    coop: [
      ['solved', { matched_count: 4, mistake_count: 1 }, 'solved'],
      ['lost', { matched_count: 2 }, 'four mistakes'],
    ],
    compete: [
      ['solved_compete', W, 'won the race'],
      ['lost_compete', {}, 'no winner'],
    ],
  },
  spellingbee: {
    playing: { found_words_score: 21, required_words_score: 50, found_words_count: 7, required_words_count: 30, target_rank: 6 },
    coop: [
      ['won', { outcome: 'target', target_rank: 6, found_words_score: 47, required_words_score: 50 }, 'reached target'],
      ['lost', { outcome: 'timeout', target_rank: 6, found_words_score: 21, required_words_score: 50, found_words_count: 7, required_words_count: 30 }, 'timeout'],
      ['ended', { outcome: 'manual', target_rank: 6, found_words_score: 21, required_words_score: 50, found_words_count: 7, required_words_count: 30 }, 'manual end'],
    ],
    compete: [
      ['won_compete', { target_rank: 6, ...W }, 'someone hit the target'],
      ['ended', { outcome: 'timeout', target_rank: 6 }, 'timeout'],
      // end_game re-emits target_rank precisely so this doesn't read "at Start".
      ['ended', { outcome: 'manual', target_rank: 6 }, 'manual end'],
      ['ended', { outcome: 'conceded', target_rank: 6 }, 'all conceded'],
    ],
  },
  wordwheel: {
    playing: { found_words_score: 21, required_words_score: 50, found_words_count: 7, required_words_count: 30, target_rank: 6 },
    coop: [
      ['won', { outcome: 'target', target_rank: 6, found_words_score: 47, required_words_score: 50 }, 'reached target'],
      ['lost', { outcome: 'timeout', target_rank: 6, found_words_score: 21, required_words_score: 50, found_words_count: 7, required_words_count: 30 }, 'timeout'],
      ['ended', { outcome: 'manual', target_rank: 6, found_words_score: 21, required_words_score: 50, found_words_count: 7, required_words_count: 30 }, 'manual end'],
    ],
    compete: [
      ['won_compete', { target_rank: 6, ...W }, 'someone hit the target'],
      ['ended', { outcome: 'timeout', target_rank: 6 }, 'timeout'],
      ['ended', { outcome: 'manual', target_rank: 6 }, 'manual end'],
      ['ended', { outcome: 'conceded', target_rank: 6 }, 'all conceded'],
    ],
  },
  // boggle only ever writes 'ended'; the OUTCOME carries the meaning.
  boggle: {
    playing: { found_words_count: 7, score: 21, leaderboard: [{}, {}] },
    shared: [
      ['ended', { outcome: 'target', found_words_count: 30, score: 90, ...W }, 'reached target'],
      ['ended', { outcome: 'timeout', found_words_count: 7, score: 21 }, 'timeout'],
      ['ended', { outcome: 'manual', found_words_count: 7, score: 21 }, 'manual end'],
    ],
  },
  bananagrams: {
    playing: {},
    shared: [
      ['won', W, 'someone went out'],
      ['lost', { outcome: 'timeout' }, 'timeout'],
      ['lost', { outcome: 'conceded' }, 'all conceded'],
    ],
  },
  waffle: {
    playing: {},
    shared: [['ended', { outcome: 'manual' }, 'manual end']],
    coop: [['won', {}, 'solved'], ['lost', {}, 'out of swaps']],
    compete: [['won_compete', W, 'someone won'], ['lost_compete', {}, 'no winner']],
  },
  wordle: {
    playing: {},
    shared: [['ended', { outcome: 'manual' }, 'manual end']],
    coop: [['won', {}, 'solved'], ['lost', {}, 'out of guesses']],
    compete: [['won_compete', W, 'someone won'], ['lost_compete', {}, 'no winner']],
  },
  stackdown: {
    playing: {},
    shared: [['ended', { outcome: 'manual' }, 'manual end']],
    coop: [['won', {}, 'cleared'], ['lost', {}, 'not cleared']],
    compete: [['won_compete', W, 'someone won'], ['lost_compete', {}, 'no winner']],
  },
  scrabble: {
    playing: { team_score: 152, bag_count: 7 },
    shared: [['ended', { outcome: 'manual' }, 'manual end']],
    coop: [['won', { team_score: 152 }, 'bag empty']],
    compete: [['won_compete', W, 'highest score'], ['lost', {}, 'all conceded']],
  },
  crosswords: {
    playing: { title: 'Sun 2026-07-04' },
    shared: [['ended', { title: 'Sun 2026-07-04', outcome: 'manual' }, 'manual end']],
    coop: [['won', { title: 'Sun 2026-07-04' }, 'solved']],
    compete: [['won_compete', { title: 'Sun 2026-07-04', ...W }, 'first to finish']],
  },
  // wordiply writes 'won_compete' only when a winner is picked; otherwise 'ended'.
  wordiply: {
    playing: { guesses_used: 2, leaderboard: [{ guesses_used: 2 }, { guesses_used: 3 }] },
    coop: [
      ['ended', { length_score: 60, letter_count: 14, outcome: 'manual' }, 'guesses used / manual end'],
      ['ended', { length_score: 60, letter_count: 14, outcome: 'timeout' }, 'timeout'],
    ],
    compete: [
      ['won_compete', { leaderboard: [{ won: true, length_score: 60 }] }, 'one winner'],
      ['won_compete', { leaderboard: [{ won: true, length_score: 60 }, { won: true, length_score: 60 }] }, 'co-winners'],
      ['ended', { outcome: 'conceded' }, 'all conceded'],
      ['ended', {}, 'no winner'],
    ],
  },
}

/** The cases a manifest can actually reach: the shared ones plus its own mode's. */
function casesFor(mode: string | undefined, fam: Family): Case[] {
  return [...(fam.shared ?? []), ...(mode === 'compete' ? (fam.compete ?? []) : (fam.coop ?? []))]
}

const row = (gametype: string, state: string, status: Record<string, unknown>): CommonGameListRow => ({
  id: 'g', gametype, play_state: state, is_terminal: state !== 'playing', status,
})

/** The markdown table body, one `| game | state | message |` row per case. */
function buildTable(): string {
  const lines = ['| game | state | status message |', '|---|---|---|']
  for (const m of games) {
    const fam = CASES[m.baseGametype]
    if (!fam) throw new Error(`No CASES entry for ${m.baseGametype} — add one (see the docstring).`)
    const label = (state: string, status: Record<string, unknown>) => m.labelFor(row(m.gametype, state, status))
    lines.push(`| **${m.gametype}** | playing | \`${label('playing', fam.playing)}\` |`)
    for (const [state, status, note] of casesFor(m.mode, fam)) {
      lines.push(`| | ${state} — ${note} | \`${label(state, status)}\` |`)
    }
  }
  return lines.join('\n')
}

describe('game status labels', () => {
  it('docs/game-status-labels.md is up to date', () => {
    const doc = readFileSync(DOC, 'utf8')
    const [head, rest] = doc.split(BEGIN)
    const [, tail] = rest.split(END)
    const next = `${head}${BEGIN}\n\n${buildTable()}\n\n${END}${tail}`

    if (process.env.REPORT === '1') {
      writeFileSync(DOC, next)
      return
    }
    expect(
      next === doc,
      `${DOC} is stale — a labelFor changed (or a game was added).\n` +
        `Regenerate it with:  npm run report:labels`,
    ).toBe(true)
  })

  /**
   * A real invariant, not a snapshot: an unhandled play state must never render as the
   * game's IN-PROGRESS text. These four reach their in-progress string through a switch
   * `default:`, so a state they don't recognise makes a *finished* game read as `solving…`
   * (or `7 tiles left`) in the club list — quietly wrong, which is the worst kind.
   * Echoing the raw state (codenamesduet, bananagrams) is ugly but visibly wrong; a
   * distinct terminal-ish phrase (psychicnum's `lost`) at least doesn't lie about whether
   * the game is over.
   *
   * The allowlist below is today's offenders, pinned so the test guards against NEW ones
   * (the same shape as `VOCABULARY_COMPLETENESS` in cssTokens.test.ts). **It's a punch
   * list — delete each line as that game's fallback is fixed**, and the test tightens by
   * itself. Adding to it should feel like a decision, not a fix.
   */
  const UNKNOWN_READS_AS_LIVE = new Set([
    'waffle_coop', 'waffle_compete',
    'wordle_coop', 'wordle_compete',
    'stackdown_coop', 'stackdown_compete',
    'scrabble_coop', 'scrabble_compete',
  ])

  it('no NEW game renders an unknown state as its in-progress label', () => {
    const offenders: string[] = []
    const fixed: string[] = []
    for (const m of games) {
      const fam = CASES[m.baseGametype]
      if (!fam) continue
      const playing = m.labelFor(row(m.gametype, 'playing', fam.playing))
      const unknown = m.labelFor(row(m.gametype, 'a_state_from_the_future', fam.playing))
      const readsAsLive = unknown === playing
      if (readsAsLive && !UNKNOWN_READS_AS_LIVE.has(m.gametype)) {
        offenders.push(`${m.gametype} → "${unknown}"`)
      }
      if (!readsAsLive && UNKNOWN_READS_AS_LIVE.has(m.gametype)) fixed.push(m.gametype)
    }
    expect(
      offenders,
      'These render an UNKNOWN play state exactly like an in-progress one, so a finished ' +
        'game would look live in the club list. Give the fallback a distinct phrase:\n' +
        offenders.join('\n'),
    ).toEqual([])
    // Keep the punch list honest in the other direction too.
    expect(
      fixed,
      `Fixed — remove from UNKNOWN_READS_AS_LIVE: ${fixed.join(', ')}`,
    ).toEqual([])
  })
})
