import { readFileSync, writeFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { games } from './games'
import type { CommonGameListRow } from './common/lib/games'

/**
 * The club-page **status line** every game renders, per play state — generated by
 * RUNNING each manifest's `labelFor` rather than transcribing 13 implementations.
 *
 * Two jobs, one file:
 *
 *   1. **Regenerate** the table in `docs/game-status-labels.md`:
 *          npm run report:labels
 *      Rewrites everything between the GENERATED markers and passes.
 *
 *   2. **Guard** it the rest of the time: rebuild the table in memory and fail if the
 *      committed doc doesn't match. The failure is ONE message ("stale — run …"), not
 *      130 string diffs, so the doc is reviewed as a document instead of as test noise.
 *
 * Why a vitest file and not a `supabase/scripts/*.ts` run through tsx, like the other
 * generators: this one has to import the manifests, which pull in lazy React components
 * and CSS modules. Vitest already resolves both. The `REPORT=1` regenerate flag mirrors
 * `board-geometry.e2e.ts`'s `BASELINE=1`.
 *
 * **When a game gains a play state, add it to CASES.** The matrix is deliberately
 * hand-written: it encodes which states each game can actually reach and which `status`
 * keys its label reads. A generated cross-product would bury the real states in noise
 * (most games echo an "else" branch for states they never see), and silently omitting a
 * new state is exactly the drift this file exists to catch.
 */

const DOC = 'docs/game-status-labels.md'
const BEGIN = '<!-- BEGIN GENERATED status-lines — edit via `npm run report:labels`, not by hand -->'
const END = '<!-- END GENERATED status-lines -->'

const W = { winner_username: 'alice' }

/** A label row: the state, the status blob its label reads, and how to name the case. */
type Case = [state: string, status: Record<string, unknown>, note: string]
/** Cases are split by MODE because a coop manifest never sees `won_compete` and a compete
 *  one never sees coop's `won` — mixing them generates rows for unreachable states, with
 *  whatever the label's `?? 0` fallbacks invent. `shared` is for the mode-less games. */
type Family = {
  playing: Record<string, unknown>
  /** The game's frozen setup, for the labels that name a setup choice (`dict`). */
  setup?: Record<string, unknown>
  shared?: Case[]
  coop?: Case[]
  compete?: Case[]
}

/**
 * Per gametype FAMILY (baseGametype): a realistic mid-game status blob, then the terminal
 * cases that family actually reaches, per mode.
 *
 * **The status keys must match what the RPC really writes.** A missing key silently falls
 * back to the label's `?? 0` / `?? 'someone'` and prints a plausible-looking lie — that is
 * not a hypothetical: an early version of this matrix omitted spellingbee's `target_rank`
 * on manual end and "found" a bug that the SQL had already fixed (it re-emits target_rank
 * for exactly this reason; see the comment in spellingbee.end_game). Check the RPC before
 * adding a case.
 */
const CASES: Record<string, Family> = {
  // No siblings — one manifest, one vocabulary.
  codenamesduet: {
    playing: { greens_found: 12, turns_remaining: 5 },
    shared: [
      ['sudden_death', { greens_found: 12 }, 'sudden death'],
      ['won', { greens_found: 15 }, 'won'],
      ['lost_assassin', { greens_found: 12 }, 'assassin'],
      ['lost_clock', { greens_found: 12 }, 'out of turns'],
      ['lost_timeout', { greens_found: 12 }, 'timeout'],
      ['ended', { greens_found: 12 }, 'manual end'],
    ],
  },
  psychicnum: {
    playing: { guesses_remaining: 5, found_secrets_count: 2, required_secrets_count: 3 },
    shared: [['ended', { outcome: 'manual', found_secrets_count: 2, required_secrets_count: 3 }, 'manual end']],
    coop: [
      ['won', W, 'found it'],
      ['lost', { outcome: 'exhausted', found_secrets_count: 2, required_secrets_count: 3 }, 'out of guesses'],
      ['lost', { outcome: 'timeout', found_secrets_count: 2, required_secrets_count: 3 }, 'timeout'],
    ],
    compete: [
      ['won_compete', W, 'won the race'],
      ['lost_compete', { outcome: 'exhausted' }, 'budgets exhausted'],
      ['lost_compete', { outcome: 'timeout' }, 'timeout'],
      ['lost_compete', { outcome: 'conceded' }, 'all conceded'],
    ],
  },
  connections: {
    playing: { matched_count: 2, mistake_count: 1 },
    shared: [['ended', { outcome: 'manual', matched_count: 2 }, 'manual end']],
    coop: [
      ['won', { matched_count: 4, mistake_count: 1 }, 'solved'],
      ['lost', { outcome: 'mistakes', matched_count: 2 }, 'four mistakes'],
      ['lost', { outcome: 'timeout', matched_count: 2 }, 'timeout'],
    ],
    compete: [
      ['won_compete', W, 'won the race'],
      ['lost_compete', { outcome: 'mistakes' }, 'everyone hit four mistakes'],
      ['lost_compete', { outcome: 'timeout' }, 'timeout'],
      ['lost_compete', { outcome: 'conceded' }, 'all conceded'],
    ],
  },
  spellingbee: {
    playing: { found_words_score: 21, required_words_score: 50, found_words_count: 7, required_words_count: 30, target_rank: 6 },
    coop: [
      ['won', { outcome: 'target', target_rank: 6, found_words_score: 47, required_words_score: 50 }, 'reached target'],
      ['lost', { outcome: 'timeout', target_rank: 6, found_words_score: 21, required_words_score: 50, found_words_count: 7, required_words_count: 30 }, 'timeout, target set'],
      ['ended', { outcome: 'timeout', target_rank: null, found_words_score: 21, required_words_score: 50, found_words_count: 7, required_words_count: 30 }, 'timeout, no target'],
      ['ended', { outcome: 'manual', target_rank: 6, found_words_score: 21, required_words_score: 50, found_words_count: 7, required_words_count: 30 }, 'manual end'],
    ],
    compete: [
      ['won_compete', { target_rank: 6, ...W }, 'someone hit the target'],
      // end_game re-emits target_rank precisely so this doesn't read "at Start".
      ['lost_compete', { outcome: 'timeout', target_rank: 6 }, 'timeout'],
      ['ended', { outcome: 'manual', target_rank: 6 }, 'manual end'],
      ['lost_compete', { outcome: 'conceded' }, 'all conceded'],
    ],
  },
  wordwheel: {
    playing: { found_words_score: 21, required_words_score: 50, found_words_count: 7, required_words_count: 30, target_rank: 6 },
    coop: [
      ['won', { outcome: 'target', target_rank: 6, found_words_score: 47, required_words_score: 50 }, 'reached target'],
      ['lost', { outcome: 'timeout', target_rank: 6, found_words_score: 21, required_words_score: 50, found_words_count: 7, required_words_count: 30 }, 'timeout, target set'],
      ['ended', { outcome: 'timeout', target_rank: null, found_words_score: 21, required_words_score: 50, found_words_count: 7, required_words_count: 30 }, 'timeout, no target'],
      ['ended', { outcome: 'manual', target_rank: 6, found_words_score: 21, required_words_score: 50, found_words_count: 7, required_words_count: 30 }, 'manual end'],
    ],
    compete: [
      ['won_compete', { target_rank: 6, ...W }, 'someone hit the target'],
      ['lost_compete', { outcome: 'timeout', target_rank: 6 }, 'timeout'],
      ['ended', { outcome: 'manual', target_rank: 6 }, 'manual end'],
      ['lost_compete', { outcome: 'conceded' }, 'all conceded'],
    ],
  },
  // boggle's terminal state now depends on whether a TARGET was set —
  // setup.win_percent, which the label reads off the row's setup.
  boggle: {
    playing: { found_words_count: 7, found_words_score: 21, leaderboard: [{}, {}] },
    setup: { win_percent: 65 },
    coop: [
      ['won', { outcome: 'target', found_words_count: 30, found_words_score: 90 }, 'reached target'],
      ['lost', { outcome: 'timeout', found_words_count: 7, found_words_score: 21 }, 'timeout, target set'],
      ['ended', { outcome: 'timeout', found_words_count: 7, found_words_score: 21 }, 'timeout, no target'],
      ['ended', { outcome: 'manual', found_words_count: 7, found_words_score: 21 }, 'manual end'],
    ],
    compete: [
      ['won_compete', { outcome: 'target', ...W }, 'reached target'],
      ['won_compete', { outcome: 'timeout', top_score: 90, ...W }, 'top score at the buzzer (no target)'],
      ['won_compete', { outcome: 'timeout', top_score: 90 }, 'tied top score (no target)'],
      ['lost_compete', { outcome: 'timeout' }, 'timeout, target set'],
      ['lost_compete', { outcome: 'timeout', leaderboard: [] }, 'timeout, nobody scored'],
      ['ended', { outcome: 'manual' }, 'manual end'],
      ['lost_compete', { outcome: 'conceded' }, 'all conceded'],
    ],
  },
  bananagrams: {
    playing: { bunch_remaining: 12 },
    shared: [
      ['won', W, 'someone went out'],
      ['lost', { outcome: 'timeout' }, 'timeout'],
      ['lost', { outcome: 'conceded' }, 'all conceded'],
      ['ended', { outcome: 'manual' }, 'manual end'],
    ],
  },
  waffle: {
    playing: { swaps_used: 4, max_swaps: 12 },
    setup: { difficulty: 3 },
    shared: [
      ['ended', { outcome: 'manual' }, 'manual end'],
      ['ended', { outcome: 'revealed' }, 'answer revealed'],
    ],
    coop: [
      ['won', { swaps_used: 9, max_swaps: 12 }, 'solved'],
      ['lost', { outcome: 'exhausted' }, 'out of swaps'],
      ['lost', { outcome: 'timeout' }, 'timeout'],
    ],
    compete: [
      ['won_compete', { outcome: 'solved', winner_swaps: 8, ...W }, 'someone won'],
      ['lost_compete', { outcome: 'exhausted' }, 'everyone out of swaps'],
      ['lost_compete', { outcome: 'timeout' }, 'timeout'],
      ['lost_compete', { outcome: 'conceded' }, 'all conceded'],
    ],
  },
  wordle: {
    playing: { guesses_used: 3, max_guesses: 6 },
    setup: { answer_source: 0 },
    shared: [
      ['ended', { outcome: 'manual' }, 'manual end'],
      ['ended', { outcome: 'revealed' }, 'answer revealed'],
    ],
    coop: [
      ['won', { outcome: 'solved', guesses_used: 4, max_guesses: 6 }, 'solved'],
      ['lost', { outcome: 'exhausted', guesses_used: 6, max_guesses: 6 }, 'out of guesses'],
      ['lost', { outcome: 'timeout', guesses_used: 3, max_guesses: 6 }, 'timeout'],
    ],
    compete: [
      ['won_compete', { outcome: 'solved', winner_guesses: 4, ...W }, 'someone won'],
      ['lost_compete', { outcome: 'exhausted' }, 'everyone out of guesses'],
      ['lost_compete', { outcome: 'timeout' }, 'timeout'],
      ['lost_compete', { outcome: 'conceded' }, 'all conceded'],
    ],
  },
  stackdown: {
    playing: { found_words_count: 3, required_words_count: 6 },
    setup: { band: 3 },
    shared: [['ended', { outcome: 'manual', found_words_count: 3, required_words_count: 6 }, 'manual end']],
    coop: [
      ['won', { outcome: 'cleared', found_words_count: 6, required_words_count: 6 }, 'cleared'],
      // The clock is stackdown's ONLY loss — no move budget, and every board
      // is guaranteed clearable.
      ['lost', { outcome: 'timeout', found_words_count: 3, required_words_count: 6 }, 'timeout'],
    ],
    compete: [
      ['won_compete', W, 'someone won'],
      ['lost_compete', { outcome: 'timeout' }, 'timeout'],
      ['lost_compete', { outcome: 'conceded' }, 'all conceded'],
    ],
  },
  scrabble: {
    playing: { team_score: 152, bag_count: 7 },
    shared: [['ended', { outcome: 'manual', team_score: 152 }, 'manual end']],
    coop: [
      // No coop win state: every finish is `ended`, only the clock loses.
      ['ended', { outcome: 'complete', team_score: 152 }, 'bag empty'],
      ['ended', { outcome: 'blocked', team_score: 152 }, 'six scoreless turns'],
      ['lost', { outcome: 'timeout', team_score: 152 }, 'timeout'],
    ],
    compete: [
      ['won_compete', { winner_score: 312, ...W }, 'highest score'],
      ['lost_compete', { outcome: 'conceded' }, 'all conceded'],
    ],
  },
  crosswords: {
    playing: { title: 'Sun 2026-07-04' },
    shared: [['ended', { outcome: 'manual' }, 'manual end']],
    coop: [
      ['won', {}, 'solved'],
      ['lost', { outcome: 'timeout' }, 'timeout'],
    ],
    compete: [
      ['won_compete', W, 'first to finish'],
      ['lost_compete', { outcome: 'timeout' }, 'timeout'],
      ['lost_compete', { outcome: 'conceded' }, 'all conceded'],
    ],
  },
  // wordiply writes 'won_compete' only when a winner is picked; otherwise 'ended'.
  wordiply: {
    playing: { guesses_used: 2, leaderboard: [{ guesses_used: 2 }, { guesses_used: 3 }] },
    coop: [
      ['ended', { length_score: 60, letter_count: 14, outcome: 'complete' }, 'guesses used'],
      ['lost', { length_score: 60, letter_count: 14, outcome: 'timeout' }, 'timeout'],
      ['ended', { length_score: 60, letter_count: 14, outcome: 'manual' }, 'manual end'],
    ],
    compete: [
      ['won_compete', { leaderboard: [{ won: true, length_score: 60 }], ...W }, 'one winner'],
      ['won_compete', { leaderboard: [{ won: true, length_score: 60 }, { won: true, length_score: 60 }] }, 'co-winners'],
      ['lost_compete', { outcome: 'conceded' }, 'all conceded'],
      ['lost_compete', { outcome: 'timeout', leaderboard: [] }, 'timeout, nobody scored'],
      ['lost_compete', { outcome: 'complete', leaderboard: [] }, 'out of guesses, nobody scored'],
      ['ended', { outcome: 'manual' }, 'manual end'],
    ],
  },
}

/** The cases a manifest can actually reach: the shared ones plus its own mode's. */
function casesFor(mode: string | undefined, fam: Family): Case[] {
  return [...(fam.shared ?? []), ...(mode === 'compete' ? (fam.compete ?? []) : (fam.coop ?? []))]
}

const row = (
  gametype: string,
  state: string,
  status: Record<string, unknown>,
  setup: Record<string, unknown>,
): CommonGameListRow => ({
  id: 'g', gametype, play_state: state, is_terminal: state !== 'playing', status, setup,
})

/** The markdown table body, one `| game | state | message |` row per case. */
function buildTable(): string {
  const lines = ['| game | state | status message |', '|---|---|---|']
  for (const m of games) {
    const fam = CASES[m.baseGametype]
    if (!fam) throw new Error(`No CASES entry for ${m.baseGametype} — add one (see the docstring).`)
    const label = (state: string, status: Record<string, unknown>) =>
      m.labelFor(row(m.gametype, state, status, fam.setup ?? {}))
    lines.push(`| **${m.gametype}** | playing | \`${label('playing', fam.playing)}\` |`)
    for (const [state, status, note] of casesFor(m.mode, fam)) {
      lines.push(`| | ${state} — ${note} | \`${label(state, status)}\` |`)
    }
  }
  return lines.join('\n')
}

describe('game status labels', () => {
  it('docs/game-status-labels.md is up to date', () => {
    const doc = readFileSync(DOC, 'utf8')
    const [head, rest] = doc.split(BEGIN)
    const [, tail] = rest.split(END)
    const next = `${head}${BEGIN}\n\n${buildTable()}\n\n${END}${tail}`

    if (process.env.REPORT === '1') {
      writeFileSync(DOC, next)
      return
    }
    expect(
      next === doc,
      `${DOC} is stale — a labelFor changed (or a game was added).\n` +
        `Regenerate it with:  npm run report:labels`,
    ).toBe(true)
  })

  /**
   * A real invariant, not a snapshot: an unhandled play state must never render as the
   * game's IN-PROGRESS text. These four reach their in-progress string through a switch
   * `default:`, so a state they don't recognise makes a *finished* game read as `solving…`
   * (or `7 tiles left`) in the club list — quietly wrong, which is the worst kind.
   * Echoing the raw state (codenamesduet, bananagrams) is ugly but visibly wrong; a
   * distinct terminal-ish phrase (psychicnum's `lost`) at least doesn't lie about whether
   * the game is over.
   *
   * The allowlist below is today's offenders, pinned so the test guards against NEW ones
   * (the same shape as `VOCABULARY_COMPLETENESS` in cssTokens.test.ts). **It's a punch
   * list — delete each line as that game's fallback is fixed**, and the test tightens by
   * itself. Adding to it should feel like a decision, not a fix.
   */
  const UNKNOWN_READS_AS_LIVE = new Set<string>([
    // EMPTY, and worth keeping that way. All eight offenders (waffle, wordle,
    // stackdown and scrabble, both modes) were fixed in the 2026-08-01 status-
    // line pass: each label is now an exhaustive `switch` whose `default`
    // returns the raw play_state, so an unrecognised state renders visibly
    // wrong instead of quietly claiming the game is still live.
  ])

  it('no NEW game renders an unknown state as its in-progress label', () => {
    const offenders: string[] = []
    const fixed: string[] = []
    for (const m of games) {
      const fam = CASES[m.baseGametype]
      if (!fam) continue
      const setup = fam.setup ?? {}
      const playing = m.labelFor(row(m.gametype, 'playing', fam.playing, setup))
      const unknown = m.labelFor(row(m.gametype, 'a_state_from_the_future', fam.playing, setup))
      const readsAsLive = unknown === playing
      if (readsAsLive && !UNKNOWN_READS_AS_LIVE.has(m.gametype)) {
        offenders.push(`${m.gametype} → "${unknown}"`)
      }
      if (!readsAsLive && UNKNOWN_READS_AS_LIVE.has(m.gametype)) fixed.push(m.gametype)
    }
    expect(
      offenders,
      'These render an UNKNOWN play state exactly like an in-progress one, so a finished ' +
        'game would look live in the club list. Give the fallback a distinct phrase:\n' +
        offenders.join('\n'),
    ).toEqual([])
    // Keep the punch list honest in the other direction too.
    expect(
      fixed,
      `Fixed — remove from UNKNOWN_READS_AS_LIVE: ${fixed.join(', ')}`,
    ).toEqual([])
  })
})
