-- ============================================================
-- tinyspy schema — baseline
-- ============================================================
--
-- The forward definition of every `tinyspy.*` table, function,
-- index, and policy.
--
-- tinyspy is Codenames Duet for two: a cooperative word-guessing
-- game played by exactly two club members. See docs/tinyspy.md
-- for the rules; the RPCs in this file are the canonical
-- implementation.
--
-- Depends on `common` (clubs, profiles, games, game_players,
-- is_club_member, gametypes). Per the removability invariant in
-- docs/naming.md, common MUST NOT reference tinyspy back.

-- ============================================================
-- Schema + usage grant
-- ============================================================

create schema if not exists tinyspy;
grant usage on schema tinyspy to authenticated;

-- ============================================================
-- tinyspy.games
-- ============================================================
-- Every game belongs to a club (the 2-member-club requirement is
-- enforced at create_game time, not by the schema — the FK is
-- just "must exist and not be deleted"). Both members are seated
-- immediately on create_game; there's no lobby state under the
-- club model.
--
-- Setup lives on common.games.setup — the canonical home for the
-- frozen-at-create-time player choices {turns, firstClueGiverUserId,
-- (future) timer}. Server-side validated in create_game.

-- tinyspy.games.id is FK'd to common.games(id) — the canonical
-- id is generated by common.create_game and passed in.
--
-- club_handle is denormalized from common.games.club_handle for RLS-
-- efficient is_club_member(club_handle) checks without a join.
--
-- Seat info (user_a_id, user_b_id, key_card_a, key_card_b) lives
-- here as columns rather than in a separate side table. The
-- two-player invariant is rock-solid (Duet rulebook), so the
-- side-table-for-arbitrary-N argument doesn't apply. A single-row
-- read gives the full game state including both seats' assignments
-- and key views. `common.game_players` separately carries the
-- "who played this game" record — the seat columns are gameplay
-- state, not authorization data.

create table tinyspy.games (
  id uuid primary key references common.games(id) on delete cascade,
  club_handle text not null references common.clubs(handle) on delete cascade,
  -- play_state lives on common.games. tinyspy's enum values:
  --   playing       — turn-based clue/guess loop (default at create).
  --   sudden_death  — timer-token-clock ran out, agents remain.
  --   won           — all 15 greens revealed (terminal).
  --   lost_assassin — assassin revealed (terminal).
  --   lost_clock    — sudden-death reveal was non-green (terminal).
  --   lost_timeout  — wall-clock countdown hit 0 (terminal).
  --
  -- `lost_timeout` is distinct from `lost_clock`: the former is
  -- the FE-driven wall-clock running out (setup.timer.countdown);
  -- the latter is the Duet rulebook's "timer tokens exhausted +
  -- a wrong sudden-death guess." Conceptually both are
  -- time-related losses but the mechanic and the UX copy differ.
  turns_remaining int not null default 9,
  turn_number int not null default 1,
  current_clue_giver text check (current_clue_giver in ('A', 'B')),
  user_a_id uuid not null references common.profiles(user_id) on delete cascade,
  user_b_id uuid not null references common.profiles(user_id) on delete cascade,
  -- jsonb arrays of exactly 25 elements each, 'G' | 'N' | 'A',
  -- indexed 0..24 matching tinyspy.words.position. Populated by
  -- create_game from the Duet key-card distribution.
  key_card_a jsonb not null,
  key_card_b jsonb not null,
  created_at timestamptz not null default now(),
  check (user_a_id <> user_b_id)
);

create index games_club_handle_idx on tinyspy.games (club_handle);

-- ============================================================
-- tinyspy.word_pool — source of words to pick 25 from
-- ============================================================
-- The actual word data is inserted at the bottom of this file
-- (after all the schema is in place, so a partial replay can't
-- leave the table empty if it crashed mid-RPC-creation).

create table tinyspy.word_pool (
  word text primary key
);

-- ============================================================
-- tinyspy.words — the 25 words drawn at game-create time
-- ============================================================
-- Per-game per-position record of which word is at which board
-- position, plus reveal state (set by submit_guess).

create table tinyspy.words (
  game_id uuid not null references tinyspy.games(id) on delete cascade,
  position int not null check (position between 0 and 24),
  word text not null,
  revealed_by text check (revealed_by in ('A', 'B')),
  revealed_as text check (revealed_as in ('G', 'N', 'A')),
  revealed_at timestamptz,
  revealed_in_turn int,
  primary key (game_id, position)
);

-- ============================================================
-- tinyspy.clues — append-only log of clues given
-- ============================================================
-- Unique constraint on (game_id, turn_number) means one clue per
-- turn, which submit_clue checks explicitly with a clearer error
-- message before the constraint would fire.

create table tinyspy.clues (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references tinyspy.games(id) on delete cascade,
  turn_number int not null,
  by_seat text not null check (by_seat in ('A', 'B')),
  word text not null,
  count int not null check (count >= 0),
  submitted_at timestamptz not null default now(),
  unique (game_id, turn_number)
);

-- ============================================================
-- RLS
-- ============================================================
-- Same shape as psychicnum + wordknit: SELECT gated on
-- is_club_member(club_handle). History is club-wide — any club member
-- can see every game in the club, regardless of whether they sat
-- down at this specific game. "Is in this game" is a gameplay
-- question handled by require_game_player at the RPC layer for
-- actions, not a visibility question.
--
-- INTENTIONAL: this policy allows any club member to read the
-- key_card_a and key_card_b columns. Under the friends-trust
-- model that's accepted — the FE only displays the caller's own
-- key column. For a hardened version, restrict to a column-grant
-- list excluding key_card_b for seat-A callers (and vice versa)
-- via a generated view. Deferred — see docs/deferred.md → tinyspy.

alter table tinyspy.games     enable row level security;
alter table tinyspy.word_pool enable row level security;
alter table tinyspy.words     enable row level security;
alter table tinyspy.clues     enable row level security;

create policy games_select on tinyspy.games
  for select to authenticated
  using (common.is_club_member(club_handle));

create policy words_select on tinyspy.words
  for select to authenticated
  using (
    exists (
      select 1 from tinyspy.games g
       where g.id = words.game_id
         and common.is_club_member(g.club_handle)
    )
  );

create policy clues_select on tinyspy.clues
  for select to authenticated
  using (
    exists (
      select 1 from tinyspy.games g
       where g.id = clues.game_id
         and common.is_club_member(g.club_handle)
    )
  );

-- No insert/update/delete policies on any table. All writes go
-- through RPCs. word_pool has no policies at all — only
-- security-definer RPCs read from it.

grant select on tinyspy.games to authenticated;
grant select on tinyspy.words to authenticated;
grant select on tinyspy.clues to authenticated;

-- ============================================================
-- Realtime publication
-- ============================================================

alter publication supabase_realtime add table tinyspy.games;
alter publication supabase_realtime add table tinyspy.words;
alter publication supabase_realtime add table tinyspy.clues;

-- ============================================================
-- tinyspy._end_turn — internal helper
-- ============================================================
-- Advances the turn counter and swaps the clue-giver. Also handles
-- the "last timer token spent → sudden death" transition. Called
-- by submit_guess (after a non-green-non-assassin reveal) and
-- pass_turn (after a clue was given but no guesses taken).

create function tinyspy._end_turn(target_game uuid)
returns void
language plpgsql
security definer
set search_path = tinyspy, common, public, extensions
as $$
declare
  remaining int;
  giver text;
  new_turn_number int;
begin
  select turns_remaining, current_clue_giver
    into remaining, giver
    from tinyspy.games where id = target_game for update;

  if remaining <= 1 then
    -- Last token spent. Transition to sudden_death on common.games
    -- (the play_state authority); zero out turns_remaining + flip
    -- clue-giver on foo.games.
    update tinyspy.games
      set turns_remaining = 0,
          turn_number = turn_number + 1,
          current_clue_giver = case giver when 'A' then 'B' else 'A' end
      where id = target_game
      returning turn_number into new_turn_number;
    perform common.update_state(
      target_game,
      'sudden_death',
      jsonb_build_object(
        'turn_number', new_turn_number,
        'turns_remaining', 0
      )
    );
  else
    update tinyspy.games
      set turns_remaining = remaining - 1,
          turn_number = turn_number + 1,
          current_clue_giver = case giver when 'A' then 'B' else 'A' end
      where id = target_game
      returning turn_number into new_turn_number;
    perform common.update_state(
      target_game,
      'playing',
      jsonb_build_object(
        'turn_number', new_turn_number,
        'turns_remaining', remaining - 1
      )
    );
  end if;
end;
$$;

revoke execute on function tinyspy._end_turn(uuid) from public;

-- ============================================================
-- tinyspy.create_game(target_club, setup, player_user_ids)
-- ============================================================
-- Validates setup, picks 25 words, generates the Duet key-card
-- distribution, seats both players (the chosen first-clue-giver
-- as A, the other as B), inserts in status='active'.
--
-- player_user_ids must contain exactly 2 uuids — both must be
-- members of target_club (validated by common.create_game). For
-- tinyspy this matches the 2-player-only invariant; the manifest
-- declares `numberOfPlayers: [2, 2]`. See
-- docs/code-conventions.md → "Per-game player counts".
--
-- Setup shape:
--   {
--     "turns": 9 | 10 | 11,
--     "firstClueGiverUserId": "<uuid; must be one of player_user_ids>"
--   }
--
-- Why a jsonb setup column rather than discrete columns
-- (`starting_turns int`): the mutable counter `turns_remaining`
-- decrements during play. Looking at a finished game later, the
-- counter at 0 doesn't tell you whether the game started with 9,
-- 10, or 11. A typed-by-the-game jsonb column preserves intent
-- for end-of-game review without per-feature column churn.
--
-- Validation is server-side: this RPC inspects the jsonb shape
-- and rejects malformed payloads. The FE's TinySpySetup type is
-- advisory only — a curious client could fire any payload, and
-- the server is the only thing protecting state correctness.

create function tinyspy.create_game(
  target_club text,
  setup jsonb,
  player_user_ids uuid[]
)
returns table(id uuid)
language plpgsql
security definer
set search_path = tinyspy, common, public, extensions
as $$
declare
  new_id uuid;
  picked_words text[];
  tiles jsonb[];
  a_view text[];
  b_view text[];
  j int;
  tmp jsonb;
  s_turns int;
  s_first uuid;
  seat_a uuid;
  seat_b uuid;
  seat_a_username text;
  seat_b_username text;
  game_title text;
begin
  -- ─── Validate setup shape ────────────────────────────
  -- Missing-vs-bad-value split so each rejection has its own
  -- clear message. Otherwise PL/pgSQL's % placeholder substitutes
  -- NULL as the empty string and we'd raise "...must be 9, 10, or
  -- 11 (got )" — readable, but confusingly empty in the parens.
  if (setup->>'turns') is null then
    raise exception 'setup.turns is required' using errcode = 'P0001';
  end if;
  s_turns := (setup->>'turns')::int;
  if s_turns not in (9, 10, 11) then
    raise exception 'setup.turns must be 9, 10, or 11 (got %)', s_turns
      using errcode = 'P0001';
  end if;

  if (setup->>'firstClueGiverUserId') is null then
    raise exception 'setup.firstClueGiverUserId is required'
      using errcode = 'P0001';
  end if;
  begin
    s_first := (setup->>'firstClueGiverUserId')::uuid;
  exception when invalid_text_representation then
    raise exception 'setup.firstClueGiverUserId must be a uuid'
      using errcode = 'P0001';
  end;

  -- Timer is a per-game setup choice. Shape validation is shared
  -- across gametypes — see common.validate_timer for the exact
  -- message set ('setup.timer is required', 'kind must be ...',
  -- 'seconds must be 1..3600 (got X)', etc.). When kind=countdown,
  -- the FE's wall-clock timer counts down; expiry fires
  -- tinyspy.submit_timeout (below).
  perform common.validate_timer(setup->'timer');

  -- ─── Validate player_user_ids size + first-clue-giver ─
  -- tinyspy is intrinsically 2-player.
  if array_length(player_user_ids, 1) <> 2 then
    raise exception 'tinyspy requires exactly 2 players (got %)',
      coalesce(array_length(player_user_ids, 1), 0)
      using errcode = 'P0001';
  end if;
  if s_first <> player_user_ids[1] and s_first <> player_user_ids[2] then
    raise exception 'setup.firstClueGiverUserId must be one of player_user_ids'
      using errcode = 'P0001';
  end if;

  -- Assign A/B: first-clue-giver is A (since A always opens the
  -- game), the other is B.
  seat_a := s_first;
  seat_b := case s_first when player_user_ids[1]
                         then player_user_ids[2]
                         else player_user_ids[1] end;

  -- ─── Pick 25 words ────────────────────────────────────
  -- Pulled forward (before common.create_game) so we can use the
  -- picked words to build the title.
  select array_agg(word) into picked_words
    from (select word from tinyspy.word_pool order by random() limit 25) sub;
  if array_length(picked_words, 1) <> 25 then
    raise exception 'word_pool must contain at least 25 words'
      using errcode = 'P0001';
  end if;

  -- ─── Build title ────────────────────────────────────
  -- Format: "<seatA-username>-v-<seatB-username>: WORD1, WORD2, WORD3, WORD4"
  -- (first 4 picked words alphabetically). Cooperative game; the
  -- `-v-` is a stylized separator, not a literal "versus."
  select username into seat_a_username
    from common.profiles where user_id = seat_a;
  select username into seat_b_username
    from common.profiles where user_id = seat_b;

  game_title := seat_a_username || '-v-' || seat_b_username || ': '
    || (
      select string_agg(w, ', ' order by w)
        from (
          select unnest(picked_words) as w
          order by 1
          limit 4
        ) first4
    );

  -- Common-side coordination: validates auth + caller club-
  -- membership + both player uids are club members, inserts
  -- common.games (with title + setup) + game_players rows,
  -- returns canonical id.
  --
  -- Saved-default arg: tinyspy strips firstClueGiverUserId before
  -- saving — that's a per-game decision (who opens this round),
  -- not a per-club preference. The two fields that ARE per-club
  -- preferences (turns count, timer mode) round-trip cleanly. The
  -- dialog's auto-pick logic for firstClueGiverUserId fills the
  -- gap on next open. See docs/deferred.md → "Setup-shape
  -- evolution" for the policy on saved-shape changes.
  new_id := common.create_game(
    target_club, 'tinyspy', player_user_ids, game_title, setup,
    setup - 'firstClueGiverUserId'
  );

  -- ─── Duet key-card distribution ───────────────────────
  -- Joint distribution (25 cells total):
  --   G/G:3  G/N:5  G/A:1
  --   N/G:5  N/N:7  N/A:1
  --   A/G:1  A/N:1  A/A:1
  tiles := array[]::jsonb[];
  for i in 1..3 loop tiles := tiles || jsonb_build_object('a','G','b','G'); end loop;
  for i in 1..5 loop tiles := tiles || jsonb_build_object('a','G','b','N'); end loop;
  tiles := tiles || jsonb_build_object('a','G','b','A');
  for i in 1..5 loop tiles := tiles || jsonb_build_object('a','N','b','G'); end loop;
  for i in 1..7 loop tiles := tiles || jsonb_build_object('a','N','b','N'); end loop;
  tiles := tiles || jsonb_build_object('a','N','b','A');
  tiles := tiles || jsonb_build_object('a','A','b','G');
  tiles := tiles || jsonb_build_object('a','A','b','N');
  tiles := tiles || jsonb_build_object('a','A','b','A');

  -- Fisher-Yates shuffle.
  for i in reverse 25..2 loop
    j := 1 + floor(random() * i)::int;
    tmp := tiles[i];
    tiles[i] := tiles[j];
    tiles[j] := tmp;
  end loop;

  a_view := array[]::text[];
  b_view := array[]::text[];
  for i in 1..25 loop
    a_view := a_view || (tiles[i]->>'a');
    b_view := b_view || (tiles[i]->>'b');
  end loop;

  -- Insert the game row using the canonical id. Seats and key
  -- cards live here as columns now (not in a side table). Setup
  -- and play_state live on common.games (the latter defaults to
  -- 'playing'), not duplicated here.
  insert into tinyspy.games (
    id, club_handle, current_clue_giver, turns_remaining,
    user_a_id, user_b_id, key_card_a, key_card_b
  ) values (
    new_id, target_club, 'A', s_turns,
    seat_a, seat_b, to_jsonb(a_view), to_jsonb(b_view)
  );

  -- Seed the initial status snapshot on common.games (the
  -- duplicate-write discipline: keep the listing-visible
  -- snapshot current from t=0). play_state defaults to 'playing'
  -- on the common.games insert; this writes the gametype-
  -- specific fields the listing label might want.
  perform common.update_state(
    new_id,
    'playing',
    jsonb_build_object(
      'turn_number', 1,
      'turns_remaining', s_turns,
      'greens_found', 0
    )
  );

  -- Insert the 25 words.
  for i in 0..24 loop
    insert into tinyspy.words (game_id, position, word)
    values (new_id, i, picked_words[i+1]);
  end loop;

  return query select new_id;
end;
$$;

revoke execute on function tinyspy.create_game(text, jsonb, uuid[]) from public;
grant execute on function tinyspy.create_game(text, jsonb, uuid[]) to authenticated;

-- ============================================================
-- tinyspy.submit_clue
-- ============================================================
-- Parameter is named clue_count (not "count") to avoid shadowing
-- the SQL aggregate function. The matching column on tinyspy.clues
-- stays "count" since it's only ever referenced in column lists,
-- never as a function call.

create function tinyspy.submit_clue(target_game uuid, word text, clue_count int)
returns void
language plpgsql
security definer
set search_path = tinyspy, common, public, extensions
as $$
declare
  caller_id uuid;
  g_row tinyspy.games%rowtype;
  current_play_state text;
  caller_seat text;
begin
  select * into g_row from tinyspy.games
   where id = target_game for update;
  if not found then
    raise exception 'game not found' using errcode = 'P0002';
  end if;

  select play_state into current_play_state
    from common.games where id = target_game;

  if current_play_state <> 'playing' then
    raise exception 'clues only allowed during active play' using errcode = 'P0001';
  end if;

  -- Auth + game-player gate. See common.require_game_player —
  -- a club member who didn't sit down at this game can't submit
  -- clues, but can still watch via club-wide RLS.
  caller_id := common.require_game_player(target_game);

  -- Seat lookup is now a column read on tinyspy.games.
  caller_seat := case caller_id
                   when g_row.user_a_id then 'A'
                   when g_row.user_b_id then 'B'
                 end;

  if caller_seat <> g_row.current_clue_giver then
    raise exception 'not your turn to give a clue' using errcode = 'P0001';
  end if;

  if exists (
    select 1 from tinyspy.clues
    where game_id = target_game and turn_number = g_row.turn_number
  ) then
    raise exception 'a clue has already been submitted this turn' using errcode = 'P0001';
  end if;

  insert into tinyspy.clues (game_id, turn_number, by_seat, word, count)
  values (target_game, g_row.turn_number, caller_seat, word, clue_count);
end;
$$;

revoke execute on function tinyspy.submit_clue(uuid, text, int) from public;
grant execute on function tinyspy.submit_clue(uuid, text, int) to authenticated;

-- ============================================================
-- tinyspy.submit_guess
-- ============================================================
-- Returns the revealed label ('G' | 'N' | 'A') for caller
-- convenience. Handles all the Duet rules:
--   - whose key view labels this reveal (the clue-giver's during
--     active play; the partner's in sudden death)
--   - assassin reveal → lost_assassin
--   - non-green during sudden death → lost_clock
--   - green reveal → check win; turn continues
--   - neutral reveal during active → turn ends via _end_turn

create function tinyspy.submit_guess(target_game uuid, target_position int)
returns text
language plpgsql
security definer
set search_path = tinyspy, common, public, extensions
as $$
declare
  caller_id uuid;
  g_row tinyspy.games%rowtype;
  current_play_state text;
  caller_seat text;
  key_owner_seat text;
  key_card jsonb;
  revealed_label text;
  green_total int;
  player_results jsonb;
  end_outcome text;
begin
  if target_position < 0 or target_position > 24 then
    raise exception 'position must be 0..24' using errcode = 'P0001';
  end if;

  select * into g_row from tinyspy.games
   where id = target_game for update;
  if not found then
    raise exception 'game not found' using errcode = 'P0002';
  end if;

  select play_state into current_play_state
    from common.games where id = target_game;

  if current_play_state not in ('playing', 'sudden_death') then
    raise exception 'game is not in a guessable state' using errcode = 'P0001';
  end if;

  caller_id := common.require_game_player(target_game);
  caller_seat := case caller_id
                   when g_row.user_a_id then 'A'
                   when g_row.user_b_id then 'B'
                 end;

  -- Whose key view labels this reveal? Most subtle rule in Duet.
  --
  -- During active play: the clue-giver's view. A green agent on
  -- the clue-giver's side counts toward the 15; a neutral on
  -- their side ends the turn; an assassin on their side ends the
  -- game. The guesser's own view does NOT matter — the guess is
  -- in response to the clue-giver's clue, so the clue-giver's
  -- labels apply.
  --
  -- In sudden death: no clue-giver, but guesses are "from memory
  -- of past clues", and those clues came from the partner. So we
  -- still use the partner's view (the seat opposite the caller).
  if current_play_state = 'playing' then
    if caller_seat = g_row.current_clue_giver then
      raise exception 'you are the clue-giver this turn' using errcode = 'P0001';
    end if;
    if not exists (
      select 1 from tinyspy.clues
      where game_id = target_game and turn_number = g_row.turn_number
    ) then
      raise exception 'waiting for clue this turn' using errcode = 'P0001';
    end if;
    key_owner_seat := g_row.current_clue_giver;
  else
    key_owner_seat := case caller_seat when 'A' then 'B' else 'A' end;
  end if;

  if exists (
    select 1 from tinyspy.words
    where game_id = target_game and position = target_position and revealed_as is not null
  ) then
    raise exception 'cell already revealed' using errcode = 'P0001';
  end if;

  -- Pick the key from the column matching the labeling seat.
  key_card := case key_owner_seat
                when 'A' then g_row.key_card_a
                when 'B' then g_row.key_card_b
              end;

  revealed_label := key_card ->> target_position;

  update tinyspy.words
    set revealed_as = revealed_label,
        revealed_by = caller_seat,
        revealed_at = now(),
        revealed_in_turn = g_row.turn_number
    where game_id = target_game and position = target_position;

  -- Terminal-transition check. The three terminal cases share a
  -- common.end_game call shape — building player_results once and
  -- branching on the outcome string keeps the branches focused.
  end_outcome := null;

  -- Terminal-transition check. The three terminal cases share a
  -- common.end_game call shape — building player_results once and
  -- branching on the outcome string keeps the branches focused.
  -- Each branch nulls out current_clue_giver on foo.games but the
  -- play_state write goes through common.end_game.
  if revealed_label = 'A' then
    update tinyspy.games set current_clue_giver = null
      where id = target_game;
    end_outcome := 'lost_assassin';
  elsif current_play_state = 'sudden_death' and revealed_label <> 'G' then
    update tinyspy.games set current_clue_giver = null
      where id = target_game;
    end_outcome := 'lost_clock';
  elsif revealed_label = 'G' then
    select count(*) into green_total from tinyspy.words
      where game_id = target_game and revealed_as = 'G';
    if green_total >= 15 then
      update tinyspy.games set current_clue_giver = null
        where id = target_game;
      end_outcome := 'won';
    end if;
  end if;

  if end_outcome is not null then
    -- Cooperative outcome: both players share the same result.
    -- (Duet is co-op: you win together or you lose together.)
    select jsonb_object_agg(
             user_id::text,
             jsonb_build_object('won', end_outcome = 'won')
           )
      into player_results
      from common.game_players
     where game_id = target_game;

    -- Initial turn budget read from common.games.setup (canonical
    -- setup location) for the `turns_used` summary field.
    perform common.end_game(
      target_game,
      end_outcome,
      jsonb_build_object(
        'outcome', end_outcome,
        'turns_used',
          (select (setup->>'turns')::int
             from common.games where id = target_game)
            - g_row.turns_remaining
      ),
      player_results
    );
    return revealed_label;
  end if;

  -- Non-terminal: if this was a green reveal, the turn continues
  -- with the same clue-giver. Otherwise (neutral in active play),
  -- end the turn.
  if revealed_label <> 'G' then
    perform tinyspy._end_turn(target_game);
  else
    -- Green reveal mid-game: bump greens_found in the listing
    -- snapshot. play_state stays 'playing' or 'sudden_death'
    -- depending on the current state.
    perform common.update_state(
      target_game,
      current_play_state,
      jsonb_build_object(
        'turn_number', g_row.turn_number,
        'turns_remaining', g_row.turns_remaining,
        'greens_found',
          (select count(*) from tinyspy.words
            where game_id = target_game and revealed_as = 'G')
      )
    );
  end if;

  return revealed_label;
end;
$$;

revoke execute on function tinyspy.submit_guess(uuid, int) from public;
grant execute on function tinyspy.submit_guess(uuid, int) to authenticated;

-- ============================================================
-- tinyspy.submit_timeout — wall-clock countdown expired
-- ============================================================
-- The FE clock is browser-side (count-down ticks locally); when
-- it hits zero, the FE fires this. We flip the game to
-- `lost_timeout` (distinct from `lost_clock`, which is the
-- timer-tokens-exhausted Duet ending) and call common.end_game
-- with outcome='lost_timeout'.
--
-- Idempotency: the active-state guard means a second concurrent
-- call from another tab raises P0001 'game is not active'. The
-- FE swallows that — losing once is enough.
--
-- Mirrors wordknit.submit_timeout / psychicnum.submit_timeout —
-- see those for the rationale on FE-driven clock + idempotent
-- server flip.

create function tinyspy.submit_timeout(target_game uuid)
returns void
language plpgsql
security definer
set search_path = tinyspy, common, public, extensions
as $$
declare
  g_row tinyspy.games%rowtype;
  current_play_state text;
  player_results jsonb;
begin
  select * into g_row from tinyspy.games
   where tinyspy.games.id = target_game
   for update;
  if not found then
    raise exception 'game not found' using errcode = 'P0002';
  end if;

  -- Auth + game-player gate. See common.require_game_player.
  perform common.require_game_player(target_game);

  select play_state into current_play_state
    from common.games where id = target_game;

  if current_play_state not in ('playing', 'sudden_death') then
    raise exception 'game is not active' using errcode = 'P0001';
  end if;

  update tinyspy.games
     set current_clue_giver = null
   where tinyspy.games.id = target_game;

  -- Cooperative loss: both players lose together.
  select jsonb_object_agg(user_id::text, '{"won": false}'::jsonb)
    into player_results
    from common.game_players
   where game_id = target_game;

  -- turns_used reads from common.games.setup (canonical setup
  -- location) minus what's left.
  perform common.end_game(
    target_game,
    'lost_timeout',
    jsonb_build_object(
      'outcome', 'lost_timeout',
      'turns_used',
        (select (setup->>'turns')::int
           from common.games where id = target_game)
          - g_row.turns_remaining
    ),
    player_results
  );
end;
$$;

revoke execute on function tinyspy.submit_timeout(uuid) from public;
grant execute on function tinyspy.submit_timeout(uuid) to authenticated;

-- ============================================================
-- tinyspy.pass_turn
-- ============================================================
-- The guesser ends the turn without taking any more guesses,
-- spending one timer token. Legal even after zero guesses on the
-- turn (e.g. "the clue makes no sense, let's just move on").

create function tinyspy.pass_turn(target_game uuid)
returns void
language plpgsql
security definer
set search_path = tinyspy, common, public, extensions
as $$
declare
  caller_id uuid;
  g_row tinyspy.games%rowtype;
  current_play_state text;
  caller_seat text;
begin
  select * into g_row from tinyspy.games
   where id = target_game for update;
  if not found then
    raise exception 'game not found' using errcode = 'P0002';
  end if;

  select play_state into current_play_state
    from common.games where id = target_game;

  if current_play_state <> 'playing' then
    raise exception 'can only pass during active play' using errcode = 'P0001';
  end if;

  caller_id := common.require_game_player(target_game);
  caller_seat := case caller_id
                   when g_row.user_a_id then 'A'
                   when g_row.user_b_id then 'B'
                 end;

  if caller_seat = g_row.current_clue_giver then
    raise exception 'clue-giver cannot pass — submit a clue first' using errcode = 'P0001';
  end if;

  if not exists (
    select 1 from tinyspy.clues
    where game_id = target_game and turn_number = g_row.turn_number
  ) then
    raise exception 'waiting for clue this turn' using errcode = 'P0001';
  end if;

  perform tinyspy._end_turn(target_game);
end;
$$;

revoke execute on function tinyspy.pass_turn(uuid) from public;
grant execute on function tinyspy.pass_turn(uuid) to authenticated;

-- Terminal-transition cleanup happens inline: submit_guess
-- (and submit_timeout) call common.end_game explicitly at the
-- moment the game is decided over. No trigger-on-status-change
-- side effect — single write path keeps the termination
-- coordination (ended_at, play_state, is_terminal, status,
-- player_results) in one place.

-- ============================================================
-- tinyspy.get_clue_context — read-only RPC for the suggester
-- ============================================================
-- Returns a jsonb object with:
--   greens:         text[]  — caller's unrevealed green agents
--   neutrals:       text[]  — caller's unrevealed neutrals (avoid)
--   assassin:       text    — caller's unrevealed assassin (avoid),
--                              or null if it's already revealed
--   previous_clues: array of {word, count, by_seat, turn_number}
--
-- Authorization: caller must be the current clue-giver of an
-- active (or sudden-death) game. We do the check here so the
-- Edge Function can stay a thin orchestrator; it gets back either
-- a clean context or a clean rejection.

create function tinyspy.get_clue_context(target_game uuid)
returns jsonb
language plpgsql
security definer
set search_path = tinyspy, common, public, extensions
as $$
declare
  caller_id uuid;
  g_row tinyspy.games%rowtype;
  current_play_state text;
  caller_seat text;
  caller_key jsonb;
  ctx jsonb;
begin
  select * into g_row from tinyspy.games where id = target_game;
  if not found then
    raise exception 'game not found' using errcode = 'P0002';
  end if;

  caller_id := common.require_game_player(target_game);
  caller_seat := case caller_id
                   when g_row.user_a_id then 'A'
                   when g_row.user_b_id then 'B'
                 end;
  caller_key := case caller_seat
                  when 'A' then g_row.key_card_a
                  when 'B' then g_row.key_card_b
                end;

  select play_state into current_play_state
    from common.games where id = target_game;

  if current_play_state not in ('playing', 'sudden_death') then
    raise exception 'no suggestions outside of active play' using errcode = 'P0001';
  end if;

  if caller_seat is distinct from g_row.current_clue_giver then
    raise exception 'only the current clue-giver can request a suggestion'
      using errcode = 'P0001';
  end if;

  -- Build the context object. Each of the three category lookups
  -- uses the caller's key view (caller_key) indexed by w.position.
  -- `->>` returns the label as text ('G' | 'N' | 'A').
  select jsonb_build_object(
    'greens', coalesce((
      select jsonb_agg(w.word order by w.position)
      from tinyspy.words w
      where w.game_id = target_game
        and w.revealed_as is null
        and (caller_key->>w.position) = 'G'
    ), '[]'::jsonb),
    'neutrals', coalesce((
      select jsonb_agg(w.word order by w.position)
      from tinyspy.words w
      where w.game_id = target_game
        and w.revealed_as is null
        and (caller_key->>w.position) = 'N'
    ), '[]'::jsonb),
    'assassin', (
      select w.word
      from tinyspy.words w
      where w.game_id = target_game
        and w.revealed_as is null
        and (caller_key->>w.position) = 'A'
      limit 1
    ),
    'previous_clues', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'word', c.word,
          'count', c.count,
          'by_seat', c.by_seat,
          'turn_number', c.turn_number
        ) order by c.turn_number
      )
      from tinyspy.clues c
      where c.game_id = target_game
    ), '[]'::jsonb)
  ) into ctx;

  return ctx;
end;
$$;

revoke execute on function tinyspy.get_clue_context(uuid) from public;
grant execute on function tinyspy.get_clue_context(uuid) to authenticated;

-- ============================================================
-- Register tinyspy with common.gametypes
-- ============================================================

insert into common.gametypes (gametype) values ('tinyspy')
on conflict do nothing;

-- ============================================================
-- Seed: tinyspy.word_pool (390 Codenames Duet words)
-- ============================================================
-- Lives in this migration (rather than seed.sql) so it's applied
-- to hosted projects by `supabase db push`. `db reset` locally
-- replays migrations too, so this still seeds the local DB.
--
-- Source: https://github.com/koosvary/codenames/blob/master/word_lists/duet.txt
-- (the typo "UNIVERITY" → "UNIVERSITY" was corrected during import).
--
-- `on conflict do nothing` makes this idempotent — running the
-- migration twice (e.g. against a partially-seeded DB) is safe.

insert into tinyspy.word_pool (word) values
  ('ACE'),
  ('ALASKA'),
  ('ANCHOR'),
  ('ANT'),
  ('ANTHEM'),
  ('APRON'),
  ('ARMOR'),
  ('ARMY'),
  ('ASTRONAUT'),
  ('ATTIC'),
  ('AVALANCHE'),
  ('AXE'),
  ('BABY'),
  ('BACON'),
  ('BALLOON'),
  ('BANANA'),
  ('BARBECUE'),
  ('BASS'),
  ('BATH'),
  ('BATTLE'),
  ('BATTLESHIP'),
  ('BAY'),
  ('BEAM'),
  ('BEAN'),
  ('BEARD'),
  ('BEE'),
  ('BEER'),
  ('BENCH'),
  ('BICYCLE'),
  ('BIG BANG'),
  ('BIG BEN'),
  ('BIKINI'),
  ('BISCUIT'),
  ('BLACK HOLE'),
  ('BLACKSMITH'),
  ('BLADE'),
  ('BLIND'),
  ('BLIZZARD'),
  ('BLUES'),
  ('BOIL'),
  ('BONSAI'),
  ('BOOK'),
  ('BOSS'),
  ('BOWL'),
  ('BOWLER'),
  ('BOXER'),
  ('BRAIN'),
  ('BRASS'),
  ('BRAZIL'),
  ('BREAD'),
  ('BREAK'),
  ('BRICK'),
  ('BRIDE'),
  ('BROTHER'),
  ('BUBBLE'),
  ('BUCKET'),
  ('BULB'),
  ('BUNK'),
  ('BUTTER'),
  ('BUTTERFLY'),
  ('CABLE'),
  ('CAESAR'),
  ('CAKE'),
  ('CAMP'),
  ('CANE'),
  ('CAPTAIN'),
  ('CASTLE'),
  ('CAVE'),
  ('CHAIN'),
  ('CHALK'),
  ('CHEESE'),
  ('CHERRY'),
  ('CHIP'),
  ('CHRISTMAS'),
  ('CLEOPATRA'),
  ('CLOCK'),
  ('CLOUD'),
  ('COACH'),
  ('COAST'),
  ('COFFEE'),
  ('COLLAR'),
  ('COLUMBUS'),
  ('COMB'),
  ('COMET'),
  ('COMPUTER'),
  ('CONE'),
  ('COW'),
  ('COWBOY'),
  ('CRAB'),
  ('CRAFT'),
  ('CROW'),
  ('CRUSADER'),
  ('CRYSTAL'),
  ('CUCKOO'),
  ('CURRY'),
  ('DASH'),
  ('DELTA'),
  ('DENTIST'),
  ('DESK'),
  ('DIRECTOR'),
  ('DISK'),
  ('DOLL'),
  ('DOLLAR'),
  ('DRAWING'),
  ('DREAM'),
  ('DRESSING'),
  ('DRIVER'),
  ('DRONE'),
  ('DRUM'),
  ('DRYER'),
  ('DUST'),
  ('EAR'),
  ('EARTH'),
  ('EARTHQUAKE'),
  ('EASTER'),
  ('EDEN'),
  ('EGG'),
  ('EINSTEIN'),
  ('FARM'),
  ('FEVER'),
  ('FIDDLE'),
  ('FLAG'),
  ('FLAT'),
  ('FLOOD'),
  ('FLOOR'),
  ('FOAM'),
  ('FOG'),
  ('FROG'),
  ('FROST'),
  ('FUEL'),
  ('GANGSTER'),
  ('GEAR'),
  ('GENIE'),
  ('GLACIER'),
  ('GLASSES'),
  ('GOAT'),
  ('GOLDILOCKS'),
  ('GOLF'),
  ('GOVERNOR'),
  ('GREENHOUSE'),
  ('GROOM'),
  ('GUITAR'),
  ('GUM'),
  ('GYMNAST'),
  ('HAIR'),
  ('HALLOWEEN'),
  ('HAMBURGER'),
  ('HAMMER'),
  ('HAWAII'),
  ('HELMET'),
  ('HERCULES'),
  ('HIDE'),
  ('HIT'),
  ('HOMER'),
  ('HOSE'),
  ('HOUSE'),
  ('ICE AGE'),
  ('ICELAND'),
  ('IGLOO'),
  ('INK'),
  ('JAIL'),
  ('JELLYFISH'),
  ('JEWELER'),
  ('JOAN OF ARC'),
  ('JOCKEY'),
  ('JOKER'),
  ('JUDGE'),
  ('JUMPER'),
  ('KICK'),
  ('KILT'),
  ('KING ARTHUR'),
  ('KISS'),
  ('KITCHEN'),
  ('KNOT'),
  ('KUNG FU'),
  ('LACE'),
  ('LADDER'),
  ('LAUNDRY'),
  ('LEATHER'),
  ('LEMONADE'),
  ('LETTER'),
  ('LIGHTNING'),
  ('LIP'),
  ('LOCUST'),
  ('LOVE'),
  ('LUMBERJACK'),
  ('LUNCH'),
  ('MAGAZINE'),
  ('MAGICIAN'),
  ('MAKEUP'),
  ('MANICURE'),
  ('MAP'),
  ('MARACAS'),
  ('MARATHON'),
  ('MEDIC'),
  ('MEMORY'),
  ('MESS'),
  ('METER'),
  ('MICROWAVE'),
  ('MILE'),
  ('MILK'),
  ('MILL'),
  ('MINOTAUR'),
  ('MINUTE'),
  ('MIRROR'),
  ('MISS'),
  ('MOHAWK'),
  ('MONA LISA'),
  ('MONKEY'),
  ('MOSES'),
  ('MOSQUITO'),
  ('MOTHER'),
  ('MOUNTIE'),
  ('MUD'),
  ('MUMMY'),
  ('MUSKETEER'),
  ('MUSTARD'),
  ('NAPOLEON'),
  ('NERVE'),
  ('NEWTON'),
  ('NOAH'),
  ('NOSE'),
  ('NOTRE DAME'),
  ('NYLON'),
  ('OASIS'),
  ('ONION'),
  ('PACIFIC'),
  ('PAD'),
  ('PADDLE'),
  ('PAGE'),
  ('PAINT'),
  ('PARADE'),
  ('PARROT'),
  ('PATIENT'),
  ('PEA'),
  ('PEACH'),
  ('PEANUT'),
  ('PEARL'),
  ('PEN'),
  ('PENNY'),
  ('PENTAGON'),
  ('PEPPER'),
  ('PEW'),
  ('PIG'),
  ('PILLOW'),
  ('PINE'),
  ('PIZZA'),
  ('POCKET'),
  ('POLISH'),
  ('POLO'),
  ('POP'),
  ('POPCORN'),
  ('POTATO'),
  ('POTTER'),
  ('POWDER'),
  ('PUPPET'),
  ('PURSE'),
  ('QUACK'),
  ('QUARTER'),
  ('RADIO'),
  ('RAIL'),
  ('RAINBOW'),
  ('RAM'),
  ('RANCH'),
  ('RAT'),
  ('RAZOR'),
  ('RECORD'),
  ('REINDEER'),
  ('RICE'),
  ('RIFLE'),
  ('RIP'),
  ('RIVER'),
  ('ROAD'),
  ('RODEO'),
  ('ROLL'),
  ('ROPE'),
  ('RUBBER'),
  ('RUSSIA'),
  ('RUST'),
  ('SACK'),
  ('SADDLE'),
  ('SAHARA'),
  ('SAIL'),
  ('SALAD'),
  ('SALOON'),
  ('SALSA'),
  ('SALT'),
  ('SAND'),
  ('SANTA'),
  ('SAW'),
  ('SCARECROW'),
  ('SCRATCH'),
  ('SCROLL'),
  ('SECOND'),
  ('SHAMPOO'),
  ('SHED'),
  ('SHEET'),
  ('SHELL'),
  ('SHERLOCK'),
  ('SHERWOOD'),
  ('SHOOT'),
  ('SHORTS'),
  ('SHOULDER'),
  ('SHOWER'),
  ('SIGN'),
  ('SILK'),
  ('SISTER'),
  ('SKATES'),
  ('SKI'),
  ('SKULL'),
  ('SLED'),
  ('SLEEP'),
  ('SLING'),
  ('SLIPPER'),
  ('SLOTH'),
  ('SMOKE'),
  ('SMOOTHIE'),
  ('SNAKE'),
  ('SNAP'),
  ('SOAP'),
  ('SOUP'),
  ('SPHINX'),
  ('SPIRIT'),
  ('SPOON'),
  ('SPRAY'),
  ('SPURS'),
  ('SQUASH'),
  ('SQUIRREL'),
  ('ST.PATRICK'),
  ('STABLE'),
  ('STAMP'),
  ('STEAM'),
  ('STEEL'),
  ('STEP'),
  ('STETHOSCOPE'),
  ('STICKER'),
  ('STORM'),
  ('STORY'),
  ('STREET'),
  ('SUGAR'),
  ('SUMO'),
  ('SUN'),
  ('SWAMP'),
  ('SWEAT'),
  ('SWORD'),
  ('TANK'),
  ('TASTE'),
  ('TATTOO'),
  ('TEA'),
  ('TEAM'),
  ('TEAR'),
  ('TEXAS'),
  ('THUNDER'),
  ('TIGER'),
  ('TIN'),
  ('TIP'),
  ('TIPI'),
  ('TOAST'),
  ('TORNADO'),
  ('TRICK'),
  ('TROLL'),
  ('TUNNEL'),
  ('TURTLE'),
  ('TUTU'),
  ('TUXEDO'),
  ('UNIVERSITY'),
  ('VALENTINE'),
  ('VAMPIRE'),
  ('VENUS'),
  ('VIKING'),
  ('VIOLET'),
  ('VIRUS'),
  ('VOLCANO'),
  ('VOLUME'),
  ('WAGON'),
  ('WAITRESS'),
  ('WALRUS'),
  ('WEDDING'),
  ('WEREWOLF'),
  ('WHEEL'),
  ('WHEELCHAIR'),
  ('WHISTLE'),
  ('WINDOW'),
  ('WING'),
  ('WISH'),
  ('WIZARD'),
  ('WONDERLAND'),
  ('WOOL'),
  ('YELLOWSTONE'),
  ('ZOMBIE') on conflict do nothing;
