-- ============================================================
-- setgame — the Set-style card game (HareTrigger)
-- ============================================================
--
-- Eighty-one cards, one per combination of four attributes with three
-- values each: COUNT (1/2/3), COLOR, SHADING and SHAPE. Twelve lie
-- face-up. Three cards are a SET when every attribute is all-same or
-- all-different across them. Claim a set and it leaves the table; the
-- board tops back up to twelve, and grows by three whenever no set is
-- present. Play ends when the deck is spent and no set remains.
--
-- "setgame" is the codename — `set` is a Postgres keyword, a TypeScript
-- builtin, and on docs/naming.md's banned-generic list, so the schema,
-- folder and gametype strings are all `setgame`. The brand is
-- HareTrigger (FE only). The found thing is a CLAIM in code; only
-- player-facing copy says "set".
--
-- ───────────────────────────────────────────────────────────
-- The packing, which is why this game needs so little machinery
-- ───────────────────────────────────────────────────────────
-- A card is four base-3 digits in one smallint 0..80:
--
--     card = count*27 + color*9 + shade*3 + shape
--
-- "All-same or all-different in every attribute" is then exactly "the
-- three digits sum to 0 mod 3 in every place", so ANY TWO CARDS
-- DETERMINE THE THIRD (setgame._third). Validating a claim is one
-- arithmetic call, and asking whether a board holds a set is a PAIR
-- loop with a membership test — never a triple scan. `src/setgame/lib/
-- cards.ts` is the same algebra in TypeScript, for the board's instant
-- feedback; this file is the authority.
--
-- ───────────────────────────────────────────────────────────
-- The only secret is the undealt deck's ORDER
-- ───────────────────────────────────────────────────────────
-- Every card in play is face-up and every claim is public — there is no
-- solution to hide and no per-peer mask anywhere, which
-- makes this the plainest trust story on the roster. What must stay
-- hidden is which cards come NEXT, so `games.deck` is withheld by a
-- column grant and `games_state` is what the FE reads. Nothing unlocks
-- it, not even at terminal: the leftover order is of no interest to
-- anyone once the game is over.
--
-- Depends on `common` (clubs, profiles, games, game_players,
-- is_club_member, gametypes, create_game, update_state, end_game,
-- reset_game, concede, require_club_member, require_game_player,
-- require_player_count_max, require_valid_mode, require_valid_timer,
-- require_compete, the turn-order primitives). Per the removability
-- invariant in docs/common.md, common MUST NOT reference setgame back.
--
-- This file is SHAPE only (tables, constraints, indexes, the Realtime
-- publication, gametype registration). Behavior — RPCs, views, policies
-- and grants — lives in supabase/sql/setgame.sql and is re-applied in
-- full on every deploy. See CLAUDE.md → Where a SQL change goes.
--
-- See docs/games/setgame.md.

create schema if not exists setgame;

-- ============================================================
-- setgame.games — one row per playthrough
-- ============================================================
-- `id` is FK to `common.games(id)` — the canonical id is generated by
-- `common.create_game` and passed in. club_handle is denormalized from
-- common.games so RLS can `is_club_member(club_handle)` without a join;
-- `mode` is denormalized the same way for the sibling-manifest split.
--
-- There is no `puzzles` table and no board builder: a board is a
-- SHUFFLE, so create_game makes one inline. That puts setgame with
-- psychicnum and scrabble as the games with nothing to pre-generate.
create table setgame.games (
  id uuid primary key references common.games(id) on delete cascade,
  club_handle text not null references common.clubs(handle) on delete cascade,

  -- Sibling-manifest mode axis. The gametype string ('setgame_coop' /
  -- 'setgame_compete') and this column agree by construction.
  mode text not null check (mode in ('coop', 'compete')),

  -- Which deck: the full 81, or JUNIOR — shading dropped, so every card
  -- is solid and the deck is 27. Junior is closed under _third (the
  -- completing card of two solid cards is itself solid), which is why
  -- nothing downstream branches on it; only the deal size differs.
  deck_kind text not null check (deck_kind in ('full', 'junior')),

  -- The shuffled deck, in draw order — THE ONLY SHIELDED COLUMN. Frozen
  -- at create time and never rewritten, which is also what makes
  -- replay_board a genuine re-run of the same game rather than a new
  -- one: it rewinds deck_pos rather than reshuffling.
  deck smallint[] not null,

  -- How many of `deck` have been dealt. Cards remaining is
  -- (deck size for deck_kind) - deck_pos, and deck_kind is public, so
  -- the FE can show "45 left" without the deck itself.
  deck_pos int not null default 0 check (deck_pos >= 0),

  -- The cards face-up, IN SLOT ORDER. Position is meaningful: slot i
  -- keeps its screen position and its keyboard letter for the whole
  -- game, so a claimed card is replaced IN PLACE rather than the board
  -- closing up (which would shift every card a player was mid-scan on).
  -- Bounded at 21 because a set-free collection tops out at 20 cards —
  -- see MAX_BOARD in src/setgame/lib/cards.ts.
  board smallint[] not null check (cardinality(board) between 0 and 21),

  created_at timestamptz not null default now()
);

create index setgame_games_club_handle_idx on setgame.games (club_handle);

-- ============================================================
-- setgame.players — one row per (game, player)
-- ============================================================
-- `sets_found` is a materialized count of the player's claims. It could
-- be an aggregate over setgame.events, but it is read on every board
-- render (the compete strip, the coop team total) and written once per
-- claim, so the counter is the cheaper side of that trade.
--
-- There is no `solved` / `solved_at` here, and its absence is the shape
-- of the game: setgame has no per-player finish line. The deck running
-- dry ends the game for EVERYONE at once, and only then does anyone win
-- — so who won is decided at the terminal and written to
-- common.game_players.result, not tracked per row as play goes.
create table setgame.players (
  game_id uuid not null references setgame.games(id) on delete cascade,
  user_id uuid not null references common.profiles(user_id) on delete cascade,

  sets_found int not null default 0 check (sets_found >= 0),

  -- Hints this player cashed. Per-player rather than a game total so the
  -- turn log can say WHO asked; the info column shows the sum, which is
  -- what "everyone gets charged" means. Stays zero in compete, where
  -- hints are banned outright (free generative help would decide a race).
  --
  -- The hint ITSELF is not stored. The board is face-up and the FE holds
  -- the same algebra the server does, so a hint is a local search — it
  -- appears on the keystroke instead of after a round trip, and there is
  -- no per-peer column to mask. What IS recorded is the EVENT (see
  -- setgame.events), because a hint is part of the game's history even
  -- though the ring on the board is not.
  hints_used int not null default 0 check (hints_used >= 0),

  primary key (game_id, user_id)
);

create index setgame_players_game_id_idx on setgame.players (game_id);

-- ============================================================
-- setgame.events — the append-only game log
-- ============================================================
-- Every claim and every hint, in order. Feeds the turn log, the
-- last-set panel, the per-player counts and the history viewer.
--
-- `events` rather than `claims`, and `kind` rather than an `is_hint`
-- flag, because a hint is not a claim — a boolean on a table called
-- `claims` would mean "a claim that isn't a claim", which is exactly
-- the naming smell docs/naming.md warns about. strands and letterboxed
-- both arrived here from the same direction.
--
-- CLUB-READABLE IN BOTH MODES, with no terminal gate — unusual for a
-- compete game, and correct here: the cards were face-up on a shared
-- table and everyone watched them leave. Knowing which three a rival
-- took says nothing about what is coming, because nothing about the
-- future is on this table. The turn log and the last-set panel both show
-- everyone's rows in both modes for the same reason.
--
-- `id` is an identity bigint because ORDER IS THE STATE: the last claim
-- is max(id), and two claims committed in the same millisecond of
-- free-for-all play must still have a defined winner. submit_set also
-- locks the games row, so concurrent claims can't both spend the same
-- card.
--
create table setgame.events (
  id bigint generated always as identity primary key,
  game_id uuid not null references setgame.games(id) on delete cascade,
  user_id uuid not null references common.profiles(user_id) on delete cascade,

  -- claim — three cards taken off the table
  -- hint  — a nudge cashed, coop only. Its `cards` are what the asker was
  --         SHOWN, so one, two or three of them depending on how many
  --         times they pressed. Recorded even though the ring itself is
  --         client-side: the ring is transient UI, the asking is history.
  kind text not null check (kind in ('claim', 'hint')),

  -- A claim's three cards, in the order they were picked; or a hint's
  -- partial set. Hence 1..3 rather than exactly 3.
  cards smallint[] not null check (cardinality(cards) between 1 and 3),

  -- The board as it stood immediately AFTER this event — the whole
  -- reason the history viewer can be a lookup instead of a replay.
  --
  -- The board at event N is perfectly derivable from the frozen deck and
  -- the events before it, but only by re-running the deal: remove three,
  -- refill IN PLACE when under the floor with cards left, TAIL-COMPACT
  -- when not, then deal-to-fixpoint appending on the right. That is the
  -- subtlest logic in this game, and deriving it on the FE would mean a
  -- second implementation with nothing testing that the two agree — and
  -- when they drift the viewer shows a board that never existed, which
  -- is worse than no viewer. Twelve to twenty-one smallints a row is a
  -- cheap way to never have that problem. (strands' viewer is a filter
  -- for the same reason.)
  board_after smallint[] not null,

  created_at timestamptz not null default now()
);

create index setgame_events_game_id_idx on setgame.events (game_id, id);

-- ============================================================
-- RLS
-- ============================================================
-- Policies live in supabase/sql/setgame.sql (behavior, re-applied every
-- deploy); enabling RLS is shape and belongs here. Enabling it with no
-- policy denies everything, so the two files must ship together — which
-- they do, since a deploy applies both.

alter table setgame.games enable row level security;
alter table setgame.players enable row level security;
alter table setgame.events enable row level security;

-- ============================================================
-- Realtime publication
-- ============================================================
-- All three play tables are published, and all three must be — useGame
-- subscribes to postgres_changes on each:
--   - games carries the board itself; every claim rewrites it.
--   - players carries the counts the compete strip reads.
--   - events is the turn log, appended on every claim and hint.
--
-- Publishing all three is NOT optional tidiness: Realtime authorizes a
-- channel's postgres_changes bindings at JOIN time and rejects the
-- WHOLE subscription if ANY bound table is missing from the
-- publication. One unpublished table would silently kill live delivery
-- for the other two — writes still persist, and a manual refresh shows
-- them, which is what makes it so hard to spot. Memberships are guarded
-- centrally in tests/common/realtime_publication_test.sql.

alter publication supabase_realtime add table setgame.games;
alter publication supabase_realtime add table setgame.players;
alter publication supabase_realtime add table setgame.events;

-- ============================================================
-- Register setgame with common.gametypes
-- ============================================================
-- Sibling-manifest pair: coop and compete are two distinct gametype
-- rows sharing this one schema. create_club seeds new clubs with both;
-- create_game routes to one via the mode arg.
--
-- No `hides_solution` — that column is gone (see
-- 20260815000000_drop_solution_revealed.sql), and setgame would not
-- have wanted it anyway: there is no solution to withhold.

insert into common.gametypes (gametype, min_players) values
  ('setgame_coop', 1),
  ('setgame_compete', 2)
on conflict do nothing;

-- Backfill clubs_gametypes for every club that ALREADY EXISTS. New clubs are
-- seeded from common.default_gametypes_for_club (via create_club /
-- claim_username), but a club created before this migration has no setgame row
-- and its Start buttons never appear — the FE hides a gametype entirely when
-- the row is absent.
--
-- IT LIVES IN THE MIGRATION, and that placement is the whole point: this file
-- is applied once, where supabase/sql/ is re-applied on every deploy. The same
-- statement there would silently put setgame back every time we shipped,
-- overriding any club whose members had turned it off in the Edit-club dialog.
--
-- The `=%` test restates the solo-club half of default_gametypes_for_club's own
-- rule: a solo club (handle `=<username>`) is never enrolled in a gametype its
-- lone member cannot field. Restated rather than called, because that function
-- lives in supabase/sql/common.sql, which is applied AFTER every migration — it
-- does not exist yet when this runs on a fresh database. (bananagrams' migration
-- does the same backfill; it needed no solo test, being solo-playable and a
-- single gametype.)
--
-- Written as an EXCLUSION rather than as that function's `not like … or
-- min_players <= 1`. The two are equivalent, but the disjunction reads as though
-- solo clubs are skipped entirely — it was misread that way once already, and
-- the reader who misreads it has no easy way to check. In full:
--
--   =joel  + setgame_coop     solo, needs 1 → enrolled
--   =joel  + setgame_compete  solo, needs 2 → SKIPPED
--   all-3  + setgame_coop     friends       → enrolled
--   all-3  + setgame_compete  friends       → enrolled
insert into common.clubs_gametypes (club_handle, gametype)
select c.handle, g.gametype
  from common.clubs c
  cross join common.gametypes g
 where g.gametype in ('setgame_coop', 'setgame_compete')
   and not (c.handle like '=%' and g.min_players > 1)
on conflict do nothing;
