-- ============================================================
-- codenamesduet schema — baseline
-- ============================================================
--
-- The forward definition of every `codenamesduet.*` table, function,
-- index, and policy.
--
-- codenamesduet is Codenames Duet for two: a cooperative word-guessing
-- game played by exactly two club members. See docs/codenamesduet.md
-- for the rules; the RPCs in this file are the canonical
-- implementation.
--
-- Depends on `common` (clubs, profiles, games, game_players,
-- is_club_member, gametypes). Per the removability invariant in
-- docs/naming.md, common MUST NOT reference codenamesduet back.

-- ============================================================
-- Schema + usage grant
-- ============================================================

create schema if not exists codenamesduet;

-- ============================================================
-- codenamesduet.games
-- ============================================================
-- Every game belongs to a club (the 2-member-club requirement is
-- enforced at create_game time, not by the schema — the FK is
-- just "must exist and not be deleted"). Both members are seated
-- immediately on create_game; there's no lobby state under the
-- club model.
--
-- Setup lives on common.games.setup — the canonical home for the
-- frozen-at-create-time player choices {turns, first_clue_giver_user_id,
-- (future) timer}. Server-side validated in create_game.

-- codenamesduet.games.id is FK'd to common.games(id) — the canonical
-- id is generated by common.create_game and passed in.
--
-- club_handle is denormalized from common.games.club_handle for RLS-
-- efficient is_club_member(club_handle) checks without a join.
--
-- Seat info (user_a_id, user_b_id, key_card_a, key_card_b) lives
-- here as columns rather than in a separate side table. The
-- two-player invariant is rock-solid (Duet rulebook), so the
-- side-table-for-arbitrary-N argument doesn't apply. A single-row
-- read gives the full game state including both seats' assignments
-- and key views. `common.game_players` separately carries the
-- "who played this game" record — the seat columns are gameplay
-- state, not authorization data.

create table codenamesduet.games (
  id uuid primary key references common.games(id) on delete cascade,
  club_handle text not null references common.clubs(handle) on delete cascade,
  -- play_state lives on common.games. codenamesduet's enum values:
  --   playing       — turn-based clue/guess loop (default at create).
  --   sudden_death  — turn budget ran out, agents remain.
  --   won           — all 15 greens revealed (terminal).
  --   lost_assassin — assassin revealed (terminal).
  --   lost_clock    — sudden-death reveal was non-green (terminal).
  --   lost_timeout  — wall-clock countdown hit 0 (terminal).
  --
  -- `lost_timeout` is distinct from `lost_clock`: the former is
  -- the FE-driven wall-clock running out (setup.timer.countdown);
  -- the latter is the Duet rulebook's "turn budget exhausted +
  -- a wrong sudden-death guess." Conceptually both are
  -- time-related losses but the mechanic and the UX copy differ.
  turns_remaining int not null default 9,
  turn_number int not null default 1,
  current_clue_giver text check (current_clue_giver in ('A', 'B')),
  user_a_id uuid not null references common.profiles(user_id) on delete cascade,
  user_b_id uuid not null references common.profiles(user_id) on delete cascade,
  -- jsonb arrays of exactly 25 elements each, 'G' | 'N' | 'A',
  -- indexed 0..24 matching codenamesduet.words.position. Populated by
  -- create_game from the Duet key-card distribution.
  key_card_a jsonb not null,
  key_card_b jsonb not null,
  created_at timestamptz not null default now(),
  check (user_a_id <> user_b_id)
);

create index codenamesduet_games_club_handle_idx on codenamesduet.games (club_handle);

-- ============================================================
-- codenamesduet.word_pool — source of words to pick 25 from
-- ============================================================
-- The actual word data is inserted at the bottom of this file
-- (after all the schema is in place, so a partial replay can't
-- leave the table empty if it crashed mid-RPC-creation).

create table codenamesduet.word_pool (
  word text primary key
);

-- ============================================================
-- codenamesduet.words — the 25 words drawn at game-create time
-- ============================================================
-- Per-game per-position record of which word is at which board
-- position, plus reveal state (set by submit_guess).

create table codenamesduet.words (
  game_id uuid not null references codenamesduet.games(id) on delete cascade,
  position int not null check (position between 0 and 24),
  word text not null,
  -- GLOBAL reveal: 'G' once this word has been contacted as an agent (one of
  -- the 15), 'A' if the assassin was hit. NULL while still in play. Neutrals
  -- are deliberately NOT global — a bystander on one player's key may be the
  -- other player's agent (Duet rulebook), so a neutral only locks the guesser's
  -- own direction. See the per-seat flags below.
  revealed_as text check (revealed_as in ('G', 'A')),
  -- Per-seat bystander marks: seat A / seat B guessed this word and it came up
  -- neutral on the clue-giver's (their partner's) key. Locks the word for THAT
  -- seat only — the partner can still guess it (it may be their agent). When
  -- BOTH are true the word is dead for both, the "both neutral markers cover
  -- the word" rule. The per-guess history (for the Game Log) lives in
  -- `codenamesduet.guesses`; these two flags are the denormalized board state.
  neutral_a boolean not null default false,
  neutral_b boolean not null default false,
  primary key (game_id, position)
);

-- ============================================================
-- codenamesduet.clues — append-only log of clues given
-- ============================================================
-- Unique constraint on (game_id, turn_number) means one clue per
-- turn, which submit_clue checks explicitly with a clearer error
-- message before the constraint would fire.

create table codenamesduet.clues (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references codenamesduet.games(id) on delete cascade,
  turn_number int not null,
  by_seat text not null check (by_seat in ('A', 'B')),
  word text not null,
  count int not null check (count >= 0),
  submitted_at timestamptz not null default now(),
  unique (game_id, turn_number)
);

-- ============================================================
-- codenamesduet.guesses — append-only log of every guess
-- ============================================================
-- One row per guess (not per word). The board's per-cell state is
-- denormalized onto `codenamesduet.words` for rendering; this is the full
-- history the Game Log replays. A word can legitimately be guessed
-- TWICE — neutral by one player, then agent/neutral/assassin by the
-- other — so the per-word row can't hold the history. `guesser_seat`
-- is the seat that made the guess; `result` is the label on the (connections'
-- name for the same per-guess verdict; it also keeps the column clear of the
-- status-jsonb `outcome` key, which names why a GAME ended)
-- clue-giver's (i.e., the partner's) key.

create table codenamesduet.guesses (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references codenamesduet.games(id) on delete cascade,
  position int not null check (position between 0 and 24),
  guesser_seat text not null check (guesser_seat in ('A', 'B')),
  result text not null check (result in ('G', 'N', 'A')),
  turn_number int not null,
  guessed_at timestamptz not null default now()
);

create index codenamesduet_guesses_game_id_idx on codenamesduet.guesses (game_id);

-- ============================================================
-- RLS
-- ============================================================
-- Same shape as psychicnum + connections: SELECT gated on
-- is_club_member(club_handle). History is club-wide — any club member
-- can see every game in the club, regardless of whether they sat
-- down at this specific game. "Is in this game" is a gameplay
-- question handled by require_game_player at the RPC layer for
-- actions, not a visibility question.
--
-- INTENTIONAL: this policy allows any club member to read the
-- key_card_a and key_card_b columns. Under the friends-trust
-- model that's accepted — the FE only displays the caller's own
-- key column. For a hardened version, restrict to a column-grant
-- list excluding key_card_b for seat-A callers (and vice versa)
-- via a generated view. Deferred — see docs/deferred.md → codenamesduet.

alter table codenamesduet.games     enable row level security;
alter table codenamesduet.word_pool enable row level security;
alter table codenamesduet.words     enable row level security;
alter table codenamesduet.clues     enable row level security;
alter table codenamesduet.guesses   enable row level security;

-- ============================================================
-- Realtime publication
-- ============================================================

-- noinspection SqlResolve
alter publication supabase_realtime add table codenamesduet.games;
-- noinspection SqlResolve
alter publication supabase_realtime add table codenamesduet.words;
-- noinspection SqlResolve
alter publication supabase_realtime add table codenamesduet.clues;
-- noinspection SqlResolve
alter publication supabase_realtime add table codenamesduet.guesses;

-- ============================================================
-- Register codenamesduet with common.gametypes
-- ============================================================

-- `hides_solution`: this game keeps its answer covered when a game ends without
-- a win, so a replay of the same board is a genuine second try. The players
-- open it with the terminal Reveal (common.reveal_solution). See
-- common.md → Revealing the solution.
insert into common.gametypes (gametype, min_players, hides_solution)
values ('codenamesduet', 2, true)
on conflict do nothing;

-- ============================================================
-- Seed: codenamesduet.word_pool (390 Codenames Duet words)
-- ============================================================
-- Lives in this migration (rather than seed.sql) so it's applied
-- to hosted projects by `supabase db push`. `db reset` locally
-- replays migrations too, so this still seeds the local DB.
--
-- Source: https://github.com/koosvary/codenames/blob/master/word_lists/duet.txt
-- (the typo "UNIVERITY" → "UNIVERSITY" was corrected during import).
--
-- `on conflict do nothing` makes this idempotent — running the
-- migration twice (e.g. against a partially-seeded DB) is safe.

insert into codenamesduet.word_pool (word) values
  ('ACE'),
  ('ALASKA'),
  ('ANCHOR'),
  ('ANT'),
  ('ANTHEM'),
  ('APRON'),
  ('ARMOR'),
  ('ARMY'),
  ('ASTRONAUT'),
  ('ATTIC'),
  ('AVALANCHE'),
  ('AXE'),
  ('BABY'),
  ('BACON'),
  ('BALLOON'),
  ('BANANA'),
  ('BARBECUE'),
  ('BASS'),
  ('BATH'),
  ('BATTLE'),
  ('BATTLESHIP'),
  ('BAY'),
  ('BEAM'),
  ('BEAN'),
  ('BEARD'),
  ('BEE'),
  ('BEER'),
  ('BENCH'),
  ('BICYCLE'),
  ('BIG BANG'),
  ('BIG BEN'),
  ('BIKINI'),
  ('BISCUIT'),
  ('BLACK HOLE'),
  ('BLACKSMITH'),
  ('BLADE'),
  ('BLIND'),
  ('BLIZZARD'),
  ('BLUES'),
  ('BOIL'),
  ('BONSAI'),
  ('BOOK'),
  ('BOSS'),
  ('BOWL'),
  ('BOWLER'),
  ('BOXER'),
  ('BRAIN'),
  ('BRASS'),
  ('BRAZIL'),
  ('BREAD'),
  ('BREAK'),
  ('BRICK'),
  ('BRIDE'),
  ('BROTHER'),
  ('BUBBLE'),
  ('BUCKET'),
  ('BULB'),
  ('BUNK'),
  ('BUTTER'),
  ('BUTTERFLY'),
  ('CABLE'),
  ('CAESAR'),
  ('CAKE'),
  ('CAMP'),
  ('CANE'),
  ('CAPTAIN'),
  ('CASTLE'),
  ('CAVE'),
  ('CHAIN'),
  ('CHALK'),
  ('CHEESE'),
  ('CHERRY'),
  ('CHIP'),
  ('CHRISTMAS'),
  ('CLEOPATRA'),
  ('CLOCK'),
  ('CLOUD'),
  ('COACH'),
  ('COAST'),
  ('COFFEE'),
  ('COLLAR'),
  ('COLUMBUS'),
  ('COMB'),
  ('COMET'),
  ('COMPUTER'),
  ('CONE'),
  ('COW'),
  ('COWBOY'),
  ('CRAB'),
  ('CRAFT'),
  ('CROW'),
  ('CRUSADER'),
  ('CRYSTAL'),
  ('CUCKOO'),
  ('CURRY'),
  ('DASH'),
  ('DELTA'),
  ('DENTIST'),
  ('DESK'),
  ('DIRECTOR'),
  ('DISK'),
  ('DOLL'),
  ('DOLLAR'),
  ('DRAWING'),
  ('DREAM'),
  ('DRESSING'),
  ('DRIVER'),
  ('DRONE'),
  ('DRUM'),
  ('DRYER'),
  ('DUST'),
  ('EAR'),
  ('EARTH'),
  ('EARTHQUAKE'),
  ('EASTER'),
  ('EDEN'),
  ('EGG'),
  ('EINSTEIN'),
  ('FARM'),
  ('FEVER'),
  ('FIDDLE'),
  ('FLAG'),
  ('FLAT'),
  ('FLOOD'),
  ('FLOOR'),
  ('FOAM'),
  ('FOG'),
  ('FROG'),
  ('FROST'),
  ('FUEL'),
  ('GANGSTER'),
  ('GEAR'),
  ('GENIE'),
  ('GLACIER'),
  ('GLASSES'),
  ('GOAT'),
  ('GOLDILOCKS'),
  ('GOLF'),
  ('GOVERNOR'),
  ('GREENHOUSE'),
  ('GROOM'),
  ('GUITAR'),
  ('GUM'),
  ('GYMNAST'),
  ('HAIR'),
  ('HALLOWEEN'),
  ('HAMBURGER'),
  ('HAMMER'),
  ('HAWAII'),
  ('HELMET'),
  ('HERCULES'),
  ('HIDE'),
  ('HIT'),
  ('HOMER'),
  ('HOSE'),
  ('HOUSE'),
  ('ICE AGE'),
  ('ICELAND'),
  ('IGLOO'),
  ('INK'),
  ('JAIL'),
  ('JELLYFISH'),
  ('JEWELER'),
  ('JOAN OF ARC'),
  ('JOCKEY'),
  ('JOKER'),
  ('JUDGE'),
  ('JUMPER'),
  ('KICK'),
  ('KILT'),
  ('KING ARTHUR'),
  ('KISS'),
  ('KITCHEN'),
  ('KNOT'),
  ('KUNG FU'),
  ('LACE'),
  ('LADDER'),
  ('LAUNDRY'),
  ('LEATHER'),
  ('LEMONADE'),
  ('LETTER'),
  ('LIGHTNING'),
  ('LIP'),
  ('LOCUST'),
  ('LOVE'),
  ('LUMBERJACK'),
  ('LUNCH'),
  ('MAGAZINE'),
  ('MAGICIAN'),
  ('MAKEUP'),
  ('MANICURE'),
  ('MAP'),
  ('MARACAS'),
  ('MARATHON'),
  ('MEDIC'),
  ('MEMORY'),
  ('MESS'),
  ('METER'),
  ('MICROWAVE'),
  ('MILE'),
  ('MILK'),
  ('MILL'),
  ('MINOTAUR'),
  ('MINUTE'),
  ('MIRROR'),
  ('MISS'),
  ('MOHAWK'),
  ('MONA LISA'),
  ('MONKEY'),
  ('MOSES'),
  ('MOSQUITO'),
  ('MOTHER'),
  ('MOUNTIE'),
  ('MUD'),
  ('MUMMY'),
  ('MUSKETEER'),
  ('MUSTARD'),
  ('NAPOLEON'),
  ('NERVE'),
  ('NEWTON'),
  ('NOAH'),
  ('NOSE'),
  ('NOTRE DAME'),
  ('NYLON'),
  ('OASIS'),
  ('ONION'),
  ('PACIFIC'),
  ('PAD'),
  ('PADDLE'),
  ('PAGE'),
  ('PAINT'),
  ('PARADE'),
  ('PARROT'),
  ('PATIENT'),
  ('PEA'),
  ('PEACH'),
  ('PEANUT'),
  ('PEARL'),
  ('PEN'),
  ('PENNY'),
  ('PENTAGON'),
  ('PEPPER'),
  ('PEW'),
  ('PIG'),
  ('PILLOW'),
  ('PINE'),
  ('PIZZA'),
  ('POCKET'),
  ('POLISH'),
  ('POLO'),
  ('POP'),
  ('POPCORN'),
  ('POTATO'),
  ('POTTER'),
  ('POWDER'),
  ('PUPPET'),
  ('PURSE'),
  ('QUACK'),
  ('QUARTER'),
  ('RADIO'),
  ('RAIL'),
  ('RAINBOW'),
  ('RAM'),
  ('RANCH'),
  ('RAT'),
  ('RAZOR'),
  ('RECORD'),
  ('REINDEER'),
  ('RICE'),
  ('RIFLE'),
  ('RIP'),
  ('RIVER'),
  ('ROAD'),
  ('RODEO'),
  ('ROLL'),
  ('ROPE'),
  ('RUBBER'),
  ('RUSSIA'),
  ('RUST'),
  ('SACK'),
  ('SADDLE'),
  ('SAHARA'),
  ('SAIL'),
  ('SALAD'),
  ('SALOON'),
  ('SALSA'),
  ('SALT'),
  ('SAND'),
  ('SANTA'),
  ('SAW'),
  ('SCARECROW'),
  ('SCRATCH'),
  ('SCROLL'),
  ('SECOND'),
  ('SHAMPOO'),
  ('SHED'),
  ('SHEET'),
  ('SHELL'),
  ('SHERLOCK'),
  ('SHERWOOD'),
  ('SHOOT'),
  ('SHORTS'),
  ('SHOULDER'),
  ('SHOWER'),
  ('SIGN'),
  ('SILK'),
  ('SISTER'),
  ('SKATES'),
  ('SKI'),
  ('SKULL'),
  ('SLED'),
  ('SLEEP'),
  ('SLING'),
  ('SLIPPER'),
  ('SLOTH'),
  ('SMOKE'),
  ('SMOOTHIE'),
  ('SNAKE'),
  ('SNAP'),
  ('SOAP'),
  ('SOUP'),
  ('SPHINX'),
  ('SPIRIT'),
  ('SPOON'),
  ('SPRAY'),
  ('SPURS'),
  ('SQUASH'),
  ('SQUIRREL'),
  ('ST.PATRICK'),
  ('STABLE'),
  ('STAMP'),
  ('STEAM'),
  ('STEEL'),
  ('STEP'),
  ('STETHOSCOPE'),
  ('STICKER'),
  ('STORM'),
  ('STORY'),
  ('STREET'),
  ('SUGAR'),
  ('SUMO'),
  ('SUN'),
  ('SWAMP'),
  ('SWEAT'),
  ('SWORD'),
  ('TANK'),
  ('TASTE'),
  ('TATTOO'),
  ('TEA'),
  ('TEAM'),
  ('TEAR'),
  ('TEXAS'),
  ('THUNDER'),
  ('TIGER'),
  ('TIN'),
  ('TIP'),
  ('TIPI'),
  ('TOAST'),
  ('TORNADO'),
  ('TRICK'),
  ('TROLL'),
  ('TUNNEL'),
  ('TURTLE'),
  ('TUTU'),
  ('TUXEDO'),
  ('UNIVERSITY'),
  ('VALENTINE'),
  ('VAMPIRE'),
  ('VENUS'),
  ('VIKING'),
  ('VIOLET'),
  ('VIRUS'),
  ('VOLCANO'),
  ('VOLUME'),
  ('WAGON'),
  ('WAITRESS'),
  ('WALRUS'),
  ('WEDDING'),
  ('WEREWOLF'),
  ('WHEEL'),
  ('WHEELCHAIR'),
  ('WHISTLE'),
  ('WINDOW'),
  ('WING'),
  ('WISH'),
  ('WIZARD'),
  ('WONDERLAND'),
  ('WOOL'),
  ('YELLOWSTONE'),
  ('ZOMBIE') on conflict do nothing;
