-- ============================================================
-- Wordknit — Connections-style word-grouping puzzle (POC)
-- ============================================================
--
-- A 4×4 board of 16 tiles split into 4 hidden categories of 4.
-- Players select 4 tiles, submit, and try to identify a category.
-- Correct guesses reveal the category as a colored band;
-- wrong/oneAway guesses cost a mistake. 4 mistakes lose; matching
-- all 4 categories wins.
--
-- "Wordknit" is the codename for the gametype (analogous to how
-- "Tinyspy" is the codename for Codenames Duet). The user-facing
-- copy can use whatever phrasing reads best; SQL / TypeScript /
-- folder names are all `wordknit`.
--
-- ┌─ POC scope ────────────────────────────────────────────┐
-- │ - Hardcoded 4-category board (words starting with      │
-- │   A/B/C/D)                                             │
-- │ - 4-mistake-lose, oneAway feedback, dup-doesn't-count  │
-- │ - Reveal-on-loss: the FE reads board.categories        │
-- │   directly, no separate RPC needed (see "FE-knows"     │
-- │   note below)                                          │
-- │ - Realtime via Postgres Changes for games + guesses +  │
-- │   Broadcast for shared selection + Presence for "is    │
-- │   everyone here" gate                                  │
-- │ - No: hint, scratchpad, peer animations, calendar,     │
-- │   share dialog, "play next," shuffle, dup-banner stale │
-- │   detection, puzzle archive, paywall                   │
-- └────────────────────────────────────────────────────────┘
--
-- ┌─ The "FE-knows-the-answer" design decision ────────────┐
-- │ Unlike tinyspy and psychic-num — where the server      │
-- │ holds a secret and validates moves against it — the    │
-- │ wordknit board (categories + tile order) is publicly   │
-- │ readable. The FE has the answer key and evaluates      │
-- │ guesses locally. The submit_guess RPC trusts the FE's  │
-- │ verdict (correct / oneAway / wrong + the matched       │
-- │ category's rank) and just records it, applying         │
-- │ atomicity for shared state (mistake_count, and one-    │
-- │ correct-per-rank idempotency via a partial unique      │
-- │ index on guesses).                                     │
-- │                                                        │
-- │ Why: the evaluator is a small pure function (~15 lines │
-- │ of TS), nothing on the board is genuinely secret in    │
-- │ this codebase's deployment, and the friends-only audi- │
-- │ ence per CLAUDE.md doesn't justify column-grant +      │
-- │ PL/pgSQL evaluation infrastructure. Psychic-num's      │
-- │ column-grant pattern is documented as the canonical    │
-- │ "true server-side secret" example; reading that file   │
-- │ is enough — repeating the pattern here for a non-      │
-- │ secret game would be educational noise.                │
-- │                                                        │
-- │ If this game ever ships beyond friends, the migration  │
-- │ to flip back is: hide `board` via column-level grant,  │
-- │ add a server-side evaluator in PL/pgSQL, drop the FE's │
-- │ `result` / `matched_category_rank` parameters from     │
-- │ submit_guess.                                          │
-- └────────────────────────────────────────────────────────┘
--
-- Depends on `common` (clubs, profiles, games, game_players,
-- is_club_member, gametypes). Per the removability invariant in
-- docs/common.md, common MUST NOT reference wordknit back.

-- ============================================================
-- Schema + usage grant
-- ============================================================

create schema if not exists wordknit;
grant usage on schema wordknit to authenticated;

-- ============================================================
-- wordknit.games
-- ============================================================
-- One row per playthrough. `board` is jsonb with shape
--   {
--     "categories": [{rank: 0..3, name: text, tiles: text[4]}, ...4],
--     "tileOrder":  [text, text, ...16]
--   }
-- The whole board is publicly readable (see the "FE-knows" note
-- in the file header). Mutable state (mistake_count, status)
-- lives in normal columns so it can be partial-updated
-- atomically.
--
-- (Setup lives on common.games.setup — the canonical home for the
-- frozen-at-create-time player choices. Wordknit's setup today is
-- just `{ "timer": ... }`; future fields like the puzzle date will
-- land alongside. Server-side validated in create_game.)

-- wordknit.games.id is now FK'd to common.games(id) — the canonical
-- id is generated by common.create_game and passed in. ON DELETE
-- CASCADE means a row here goes away if its common.games parent
-- is deleted (e.g., the gametype is unregistered).
--
-- club_id stays on this row (denormalized from common.games.club_id)
-- so the RLS policy can ask is_club_member(club_id) without a join.
-- The denormalization is safe — club_id is set at create-game time
-- and never changes.

-- ============================================================
-- wordknit.puzzles — the source-of-truth puzzle library
-- ============================================================
-- A *puzzle* is a prewritten, replayable board shape: one date's
-- NYT Connections puzzle, imported from the Eyefyre/
-- NYT-Connections-Answers repo via the npm `puzzles:import`
-- script. Distinct from a *game's* `board` jsonb (below), which
-- is the per-game-instance copy plus that game's shuffled
-- `tileOrder`. Puzzles stay pristine; games copy from them.
--
-- Two unique identifiers we preserve from NYT:
--   - `source_id` — the NYT puzzle number ("1", "500"). Text
--     because it's used as a number-in-display but a future NYT
--     could publish "500-bonus" without breaking the schema.
--   - `nyt_date`  — the calendar date NYT published. Drives the
--     setup-form date picker.
--
-- `categories` is a jsonb array matching the shape of
-- `wordknit.games.board.categories`:
--     [{ rank: 0..3, name: text, tiles: text[4] }, …]
-- The importer normalizes the NYT shape (rank from array index,
-- name from `group`, tiles from `members`).

create table wordknit.puzzles (
  id uuid primary key default gen_random_uuid(),
  source_id text not null unique,
  nyt_date date not null unique,
  categories jsonb not null,
  imported_at timestamptz not null default now()
);

-- Public knowledge — puzzles aren't sensitive. The setup-form
-- date picker reads this list to render available dates; the
-- create_game RPC reads `categories` to build the board.
grant select on wordknit.puzzles to authenticated;

-- The puzzle-import script (supabase/scripts/import-wordknit-
-- puzzles.ts) connects as the service_role and needs USAGE on
-- the schema + INSERT on this table. authenticated has no INSERT
-- grant; writes go through service_role only.
grant usage on schema wordknit to service_role;
grant insert, select on wordknit.puzzles to service_role;

create table wordknit.games (
  id uuid primary key references common.games(id) on delete cascade,
  club_id uuid not null references common.clubs(id) on delete cascade,
  -- The puzzle this game was created from. ON DELETE RESTRICT
  -- because deleting a puzzle that has games against it would
  -- leave dangling references — alpha-stage policy is "clean up
  -- games first, then drop the puzzle." Set at create_game time;
  -- never updated.
  puzzle_id uuid not null references wordknit.puzzles(id) on delete restrict,
  -- play_state lives on common.games. Wordknit's enum values are
  -- 'playing' / 'solved' / 'lost' (covering both
  -- 4-mistakes-loss and wall-clock-timeout-loss; the distinction
  -- lives in common.games.status.outcome).
  mistake_count int not null default 0
    check (mistake_count between 0 and 4),
  -- Frozen per-game copy of the puzzle's categories + this game's
  -- shuffled tileOrder. Keeping the copy means the played board is
  -- self-contained: if the source puzzle row were ever corrected
  -- upstream and re-imported, in-flight games stay on the version
  -- they started with.
  board jsonb not null,
  created_at timestamptz not null default now()
);

create index wordknit_games_club_id_idx on wordknit.games (club_id);
create index wordknit_games_puzzle_id_idx on wordknit.games (puzzle_id);

-- ============================================================
-- wordknit.guesses — append-only log
-- ============================================================
-- One row per submit. `matched_category_rank` is non-null iff
-- result = 'correct' — the rank (0..3) of the category that was
-- matched. Duplicate submissions (same 4-tile set) are filtered
-- on the FE side (the client has full game state including the
-- guess log), so the RPC just records what it's told.

create table wordknit.guesses (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references wordknit.games(id) on delete cascade,
  user_id uuid not null references common.profiles(user_id) on delete cascade,
  tiles text[] not null,
  result text not null check (result in ('correct', 'oneAway', 'wrong')),
  matched_category_rank int
    check (matched_category_rank between 0 and 3),
  guessed_at timestamptz not null default now()
);

create index wordknit_guesses_game_id_idx on wordknit.guesses (game_id);

-- One-correct-per-rank-per-game: partial unique index over the
-- 'correct' rows of `guesses`. This is the race idempotency
-- enforcer — when two players both submit a correct guess for
-- the same category at the same instant, the second INSERT
-- raises unique_violation, which submit_guess catches and
-- treats as "already matched, no-op."
--
-- The set of matched categories is fully derivable from
-- `guesses` filtered to result='correct' plus the static board,
-- so there's no separate matched-categories table — the partial
-- index gives the same idempotency property with one fewer
-- table to fan postgres-changes events out of.
create unique index wordknit_guesses_one_correct_per_rank
  on wordknit.guesses (game_id, matched_category_rank)
  where result = 'correct';

-- ============================================================
-- RLS
-- ============================================================
-- Same shape as psychic-num: SELECT gated on club membership,
-- no INSERT/UPDATE/DELETE policies (writes go through the
-- security-definer RPCs).

alter table wordknit.games enable row level security;
alter table wordknit.guesses enable row level security;

create policy games_select on wordknit.games
  for select to authenticated
  using (common.is_club_member(club_id));

create policy guesses_select on wordknit.guesses
  for select to authenticated
  using (
    exists (
      select 1 from wordknit.games g
       where g.id = guesses.game_id
         and common.is_club_member(g.club_id)
    )
  );

grant select on wordknit.games to authenticated;
grant select on wordknit.guesses to authenticated;

-- ============================================================
-- Realtime publication
-- ============================================================
-- Two tables broadcast so the FE can subscribe to:
--   games    status flips, mistake_count increments
--   guesses  new guess submissions (including correct ones —
--            which is how the FE learns a category was matched,
--            now that there's no separate found_groups table)

alter publication supabase_realtime add table wordknit.games;
alter publication supabase_realtime add table wordknit.guesses;

-- ============================================================
-- wordknit.create_game — start a new game in a club
-- ============================================================
-- Validates the setup shape, looks up the puzzle by id, builds
-- the per-game board (the puzzle's categories + a freshly-shuffled
-- tileOrder), then coordinates the two-write game-creation:
--
--   1. common.create_game(target_club, 'wordknit', player_user_ids,
--                          title, setup)
--      — validates caller is in the club, validates every uid in
--      player_user_ids is in clubs_members, vacates any prior
--      current-view game for this club, inserts the common.games
--      header row (with is_current_view=true, play_state='playing')
--      + one common.game_players row per uid, returns the
--      canonical game id.
--   2. INSERT INTO wordknit.games using that id — landing the
--      gametype-specific board + puzzle reference.
--
-- player_user_ids is the explicit list of who's actually playing
-- THIS game. Defaults are not enforced server-side; the FE's
-- setup dialog defaults to all current club members but lets the
-- player pick a subset. The caller does NOT have to be in
-- player_user_ids (the "Ada facilitates a game between Bea and
-- Cade" case is supported).
--
-- Setup shape:
--   {
--     "puzzleId": "<uuid>",         -- references wordknit.puzzles(id)
--     "timer": (
--         { "kind": "none" }
--       | { "kind": "countup" }
--       | { "kind": "countdown", "seconds": <int 1..3600> }
--     )
--   }
--
-- Title formula: "#<source_id> <nyt_date> (<TILE1>/<TILE2>)" where
-- TILE1/TILE2 are the first 2 alphabetical tiles across all 16.
-- A puzzle is hard to remember by date alone; the tiles ground it
-- in something memorable ("oh, that one with BUCKS and HAIL").

create function wordknit.create_game(
  target_club uuid,
  setup jsonb,
  player_user_ids uuid[]
)
returns table(id uuid)
language plpgsql
security definer
set search_path = wordknit, common, public, extensions
as $$
declare
  new_id uuid;
  s_puzzle_id uuid;
  puzzle_row wordknit.puzzles%rowtype;
  board_categories jsonb;
  tile_order text[];
  j int;
  tmp text;
  first_two_tiles text;
  game_title text;
begin
  -- No member-count check — wordknit plays with any club size.
  -- Must agree with the `numberOfPlayers: [1, null]` declaration
  -- in src/wordknit/manifest.ts. See docs/code-conventions.md →
  -- "Per-game player counts" for the cross-reference convention.

  -- ─── Validate setup shape ────────────────────────────
  -- Missing-vs-bad-value split so each rejection has a clean,
  -- field-named message. The FE's date-picker can't normally
  -- produce these, but a curious client could send anything.
  if (setup->>'puzzleId') is null then
    raise exception 'setup.puzzleId is required' using errcode = 'P0001';
  end if;
  begin
    s_puzzle_id := (setup->>'puzzleId')::uuid;
  exception when invalid_text_representation then
    raise exception 'setup.puzzleId must be a uuid'
      using errcode = 'P0001';
  end;

  -- Canonical timer-shape validation. See common.validate_timer
  -- for the accepted shapes and the exact raise messages.
  perform common.validate_timer(setup->'timer');

  -- Load the puzzle. The FK on wordknit.games.puzzle_id would also
  -- catch a bad id at INSERT time, but a clear "puzzle not found"
  -- error is friendlier than a foreign-key violation. RLS-free
  -- read (the table has a permissive SELECT grant).
  select * into puzzle_row from wordknit.puzzles
   where wordknit.puzzles.id = s_puzzle_id;
  if not found then
    raise exception 'puzzle not found' using errcode = 'P0002';
  end if;

  board_categories := puzzle_row.categories;

  -- Extract all 16 tiles from the puzzle's categories.
  select array_agg(t)
    into tile_order
    from jsonb_array_elements(board_categories) c,
         jsonb_array_elements_text(c->'tiles') t;

  -- Title = "#<source_id> <nyt_date> (<TILE1>/<TILE2>)" where
  -- TILE1/TILE2 are the first 2 alphabetical tiles across the 16.
  -- Built BEFORE the shuffle since alphabetical order is order-
  -- independent.
  select string_agg(t, '/' order by t) into first_two_tiles
    from (
      select unnest(tile_order) as t
      order by 1
      limit 2
    ) first2;
  game_title := format('#%s %s (%s)',
                       puzzle_row.source_id,
                       puzzle_row.nyt_date,
                       first_two_tiles);

  -- Fisher-Yates shuffle for the display order.
  for i in reverse 16..2 loop
    j := 1 + floor(random() * i)::int;
    tmp := tile_order[i];
    tile_order[i] := tile_order[j];
    tile_order[j] := tmp;
  end loop;

  -- Common-side coordination: validates auth + caller membership +
  -- player_user_ids membership, inserts common.games (with title +
  -- setup) + game_players, returns the canonical id we'll use
  -- below.
  new_id := common.create_game(
    target_club, 'wordknit', player_user_ids, game_title, setup
  );

  -- Insert with the canonical id. Note: id NOT default-generated;
  -- it comes from common.create_game above and FKs to
  -- common.games(id). Setup lives on common.games.setup, not
  -- duplicated here.
  insert into wordknit.games (id, club_id, puzzle_id, board)
  values (
    new_id,
    target_club,
    s_puzzle_id,
    jsonb_build_object('categories', board_categories,
                       'tileOrder',  to_jsonb(tile_order))
  );

  return query select new_id;
end;
$$;

revoke execute on function wordknit.create_game(uuid, jsonb, uuid[]) from public;
grant execute on function wordknit.create_game(uuid, jsonb, uuid[]) to authenticated;

-- ============================================================
-- wordknit.submit_guess — record a submission
-- ============================================================
-- The FE-knows model: the caller has already evaluated the guess
-- (using the public `board.categories`) and tells us the result
-- and, when result='correct', the matched category's rank. We:
--
--   1. validate authorization + game state
--   2. light-validate the payload shape (4 tiles, valid result
--      enum, rank present iff correct)
--   3. for 'correct': insert into guesses (the partial unique
--      index on (game_id, matched_category_rank) where
--      result='correct' acts as the race-idempotency check),
--      then count correct rows to detect the win
--   4. for 'wrong' / 'oneAway': record the guess,
--      mistake_count++, check loss
--
-- The SELECT FOR UPDATE on the games row serializes concurrent
-- submissions: two players both clicking Submit at the same
-- instant both land on the same row lock, the first commits,
-- the second sees the updated state (status or mistake_count)
-- before its writes.
--
-- The matched_category_rank CHECK constraint on the column
-- (0..3) already enforces a valid range, and every board has
-- exactly 4 categories ranked 0..3 by construction — so we
-- don't need a separate runtime "rank exists in board" check.

create function wordknit.submit_guess(
  target_game uuid,
  tiles text[],
  result text,
  matched_category_rank int default null
)
returns void
language plpgsql
security definer
set search_path = wordknit, common, public, extensions
as $$
declare
  caller_id uuid;
  g_row wordknit.games%rowtype;
  current_play_state text;
  matched_count int;
  new_mistake_count int;
  player_results jsonb;
begin
  -- Lock the game row for atomic mistake_count++ and play_state
  -- flips.
  select * into g_row from wordknit.games
   where wordknit.games.id = target_game
   for update;
  if not found then
    raise exception 'game not found' using errcode = 'P0002';
  end if;

  -- Auth + game-player gate (deferred to after the lock). See
  -- common.require_game_player — checks the caller is actually
  -- IN this game (per common.game_players), not just a club
  -- member. A club member who didn't sit down at this game can
  -- still WATCH it (club-wide RLS) but can't act.
  caller_id := common.require_game_player(target_game);

  select play_state into current_play_state
    from common.games where id = target_game;

  if current_play_state <> 'playing' then
    raise exception 'game is not in progress' using errcode = 'P0001';
  end if;

  -- ─── Light payload validation ─────────────────────────
  -- Server-side checks for shape, not for rule correctness — the
  -- FE is trusted to apply the rules under the friends-only
  -- trust model (see CLAUDE.md). These guards catch malformed
  -- payloads (lengths, enum values) so the data we persist is at
  -- least well-typed.
  if tiles is null or array_length(tiles, 1) <> 4 then
    raise exception 'must submit exactly 4 tiles (got %)',
                    coalesce(array_length(tiles, 1), 0)
      using errcode = 'P0001';
  end if;

  if result not in ('correct', 'oneAway', 'wrong') then
    raise exception 'result must be correct, oneAway, or wrong (got %)', result
      using errcode = 'P0001';
  end if;

  if result = 'correct' then
    if matched_category_rank is null
       or matched_category_rank not between 0 and 3 then
      raise exception 'matched_category_rank must be 0..3 when result is correct'
        using errcode = 'P0001';
    end if;

    -- Idempotent insert: the partial unique index on
    -- (game_id, matched_category_rank) where result='correct'
    -- raises unique_violation if a peer beat us to it. We catch
    -- it and bail without erroring out to the second caller —
    -- they saw the same correct visual; recording the match
    -- once is enough. The win check is skipped on this path
    -- because the first caller's transaction already ran it.
    begin
      insert into wordknit.guesses
        (game_id, user_id, tiles, result, matched_category_rank)
      values
        (target_game, caller_id, tiles, result, matched_category_rank);
    exception when unique_violation then
      return;
    end;

    -- Win check: 4 correct guesses ⇒ all categories matched ⇒
    -- solved. The `gu` alias disambiguates `result` — the
    -- function has a parameter of the same name in scope.
    select count(*) into matched_count
      from wordknit.guesses gu
     where gu.game_id = target_game and gu.result = 'correct';
    if matched_count >= 4 then
      -- Cooperative win: every player gets {"won": true}. Build
      -- the per-player map from common.game_players for this game.
      select jsonb_object_agg(user_id::text, '{"won": true}'::jsonb)
        into player_results
        from common.game_players
       where game_id = target_game;

      perform common.end_game(
        target_game,
        'solved',
        jsonb_build_object(
          'outcome', 'solved',
          'mistake_count', g_row.mistake_count,
          'matched_count', 4
        ),
        player_results
      );
    else
      -- Non-terminal correct guess: bump the listing snapshot so
      -- the club page shows the new matched_count.
      perform common.update_state(
        target_game,
        'playing',
        jsonb_build_object(
          'mistake_count', g_row.mistake_count,
          'matched_count', matched_count
        )
      );
    end if;

    return;
  end if;

  -- Wrong / oneAway: cost a mistake.
  new_mistake_count := g_row.mistake_count + 1;

  insert into wordknit.guesses
    (game_id, user_id, tiles, result, matched_category_rank)
  values
    (target_game, caller_id, tiles, result, null);

  update wordknit.games
    set mistake_count = new_mistake_count
   where wordknit.games.id = target_game;

  -- Count current matched categories for the listing snapshot.
  select count(*) into matched_count
    from wordknit.guesses gu
   where gu.game_id = target_game and gu.result = 'correct';

  if new_mistake_count >= 4 then
    -- Cooperative loss: every player gets {"won": false}.
    select jsonb_object_agg(user_id::text, '{"won": false}'::jsonb)
      into player_results
      from common.game_players
     where game_id = target_game;

    perform common.end_game(
      target_game,
      'lost',
      jsonb_build_object(
        'outcome', 'lost_mistakes',
        'mistake_count', new_mistake_count,
        'matched_count', matched_count
      ),
      player_results
    );
  else
    perform common.update_state(
      target_game,
      'playing',
      jsonb_build_object(
        'mistake_count', new_mistake_count,
        'matched_count', matched_count
      )
    );
  end if;
end;
$$;

revoke execute on function wordknit.submit_guess(uuid, text[], text, int) from public;
grant execute on function wordknit.submit_guess(uuid, text[], text, int) to authenticated;

-- ============================================================
-- wordknit.submit_timeout — countdown expiry handler
-- ============================================================
-- Fired by the FE when the count-down timer hits 0. Sets the
-- game's status to 'lost' (same terminal status as 4-mistakes-
-- losing — the cause doesn't change the outcome shape, just the
-- copy in the loss banner; the FE can distinguish by looking at
-- the mistakes count vs. the absence of mistakes).
--
-- Concurrency: multiple clients may fire submit_timeout at the
-- same instant because each client's local timer hits 0 around
-- the same wall-clock moment. The `SELECT ... FOR UPDATE` lock
-- serializes them; whichever transaction commits first flips
-- status to 'lost'; subsequent calls see status != 'in_progress'
-- and raise P0001. The FE swallows that "already lost" rejection
-- silently — it just means a peer beat us to the punch, and
-- realtime will propagate the loss to all clients.
--
-- common.end_game handles the cross-cutting termination work
-- (play_state + is_terminal + status + per-player results).

create function wordknit.submit_timeout(target_game uuid)
returns void
language plpgsql
security definer
set search_path = wordknit, common, public, extensions
as $$
declare
  g_row wordknit.games%rowtype;
  current_play_state text;
  matched_count int;
  player_results jsonb;
begin
  select * into g_row from wordknit.games
   where wordknit.games.id = target_game
   for update;
  if not found then
    raise exception 'game not found' using errcode = 'P0002';
  end if;

  -- Auth + game-player gate. See common.require_game_player.
  perform common.require_game_player(target_game);

  select play_state into current_play_state
    from common.games where id = target_game;

  if current_play_state <> 'playing' then
    raise exception 'game is not in progress' using errcode = 'P0001';
  end if;

  -- Build cooperative loss player_results + status jsonb.
  select count(*) into matched_count
    from wordknit.guesses gu
   where gu.game_id = target_game and gu.result = 'correct';

  select jsonb_object_agg(user_id::text, '{"won": false}'::jsonb)
    into player_results
    from common.game_players
   where game_id = target_game;

  perform common.end_game(
    target_game,
    'lost',
    jsonb_build_object(
      'outcome', 'lost_timeout',
      'mistake_count', g_row.mistake_count,
      'matched_count', matched_count
    ),
    player_results
  );
end;
$$;

revoke execute on function wordknit.submit_timeout(uuid) from public;
grant execute on function wordknit.submit_timeout(uuid) to authenticated;

-- Terminal-transition cleanup happens inline: submit_guess and
-- submit_timeout call common.end_game explicitly at the moment
-- the game is decided over. Single write path keeps all the
-- termination coordination (ended_at, play_state, is_terminal,
-- status, player_results) in one place.

-- ============================================================
-- Register wordknit with common.gametypes
-- ============================================================

insert into common.gametypes (gametype) values ('wordknit')
on conflict do nothing;
