-- ============================================================
-- psychicnum schema — baseline
-- ============================================================
--
-- Psychic Num is a tiny cooperative number-guessing game: pick a
-- random target 1..10, hidden server-side; any club member can
-- guess at any time; first correct guess wins; running out of
-- guesses loses. Deliberately minimal — it exercises the
-- multi-game architecture (per-game schema, per-game theme,
-- per-game chunk split, column-level secrecy) with the absolute
-- minimum game-logic surface, so the patterns are legible
-- compared to tinyspy's richer shape.
--
-- What this exercises that tinyspy doesn't:
--   - N-player, no turns (anyone-acts-any-time)
--   - A genuine server-side secret (the target), hidden from the
--     client even with devtools open via a column-level grant
--     that excludes `target` from authenticated SELECT
--   - A simpler play_state enum (playing/won/lost — no
--     sudden_death, no multi-axis loss reasons)
--
-- The static-starting-state vocabulary calls for a "boards" table
-- in some games (boggle's dice, crosswords' grid). Psychic Num's
-- only static datum is the target number — too small to warrant
-- its own table, so it co-locates onto the game row, matching how
-- tinyspy keeps its words alongside the game.
--
-- Depends on `common` (clubs, profiles, games, game_players,
-- is_club_member, gametypes). Per the removability invariant,
-- common MUST NOT reference psychicnum back.

-- ============================================================
-- Schema + usage grant
-- ============================================================

create schema if not exists psychicnum;
grant usage on schema psychicnum to authenticated;

-- ============================================================
-- psychicnum.games — one row per playing
-- ============================================================
-- `target` is the secret 1..10; column-grant excludes it from
-- authenticated SELECT (see grants below). RPCs run as the
-- postgres role under security definer and can read it freely;
-- the FE only learns it once the game is terminal, via the
-- `psychicnum.games_state` view + `_target_for` helper pattern.
--
-- (Setup lives on common.games.setup — the player choices
-- {guesses, timer} are persisted there as one canonical blob.
-- Per-gametype create_game validates the field shape but doesn't
-- duplicate the storage.)
--
-- The `guesses_remaining between 0 and 9` constraint matches the
-- max allowed setup.guesses value.

-- psychicnum.games.id is FK'd to common.games(id) — the canonical
-- id is generated by common.create_game and passed in. ON DELETE
-- CASCADE means a row here goes away if its common.games parent
-- is deleted (e.g., the gametype is unregistered).
--
-- club_id stays on this row (denormalized from common.games.club_id)
-- so the RLS policy can ask is_club_member(club_id) without a join.

-- play_state lives on common.games now, not here. Psychic-num's
-- enum values are 'playing' / 'won' / 'lost'. Mid-game RPCs (and
-- the FE) read play_state from common.games rather than from this
-- row. See docs/states.md → "Where the two tables sit."
create table psychicnum.games (
  id uuid primary key references common.games(id) on delete cascade,
  club_id uuid not null references common.clubs(id) on delete cascade,
  target int not null check (target between 1 and 10),
  guesses_remaining int not null default 7
    check (guesses_remaining between 0 and 9),
  winner_id uuid references common.profiles(user_id) on delete set null,
  created_at timestamptz not null default now()
);

create index psychicnum_games_club_id_idx on psychicnum.games (club_id);

-- ============================================================
-- psychicnum.guesses — append-only log
-- ============================================================
-- Used both for "show the history" in the UI and for the
-- guesses_remaining counter (though we update the counter on
-- psychicnum.games inline rather than recomputing from this log,
-- to keep submit_guess cheap and to support a column-level RLS
-- story).

create table psychicnum.guesses (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references psychicnum.games(id) on delete cascade,
  user_id uuid not null references common.profiles(user_id) on delete cascade,
  number int not null check (number between 1 and 10),
  was_correct boolean not null,
  guessed_at timestamptz not null default now()
);

create index psychicnum_guesses_game_id_idx on psychicnum.guesses (game_id);

-- ============================================================
-- RLS
-- ============================================================
-- Club members can SELECT both tables. Writes never happen
-- directly — they go through the security-definer RPCs below.

alter table psychicnum.games enable row level security;
alter table psychicnum.guesses enable row level security;

-- A member of the club that owns this game can see the row.
-- (The `target` column is *additionally* hidden by a column-level
-- grant; see the grants section below.)
create policy games_select on psychicnum.games
  for select to authenticated
  using (common.is_club_member(club_id));

-- Guesses inherit visibility from their parent game.
create policy guesses_select on psychicnum.guesses
  for select to authenticated
  using (
    exists (
      select 1 from psychicnum.games g
       where g.id = guesses.game_id
         and common.is_club_member(g.club_id)
    )
  );

-- ============================================================
-- Grants — `target` is column-excluded
-- ============================================================
-- Default `grant select` would include `target`, defeating the
-- "backend-authoritative secret" property. Column-list grant
-- whitelists every column EXCEPT `target`. RPCs that need to read
-- target (the games_state view below, the game-end status_summary
-- builders) run as the postgres role and bypass this; the
-- authenticated role can never SELECT target directly.

grant select
  (id, club_id, guesses_remaining, winner_id, created_at)
  on psychicnum.games to authenticated;

grant select on psychicnum.guesses to authenticated;

-- ============================================================
-- psychicnum.games_state — FE-ready read view
-- ============================================================
-- The single thing the FE reads to render a psychic-num game's
-- gametype-specific fields. Combines what's directly readable
-- from psychicnum.games with the conditional `target` reveal:
--
--   - While the game's play_state is 'playing', target is NULL.
--   - Once play_state flips terminal ('won' or 'lost'), target
--     is the real 1..10 value.
--
-- play_state itself lives on common.games and is read by the FE
-- via useCommonGame — this view does NOT include it. The view's
-- only job is gametype-specific data + the gated reveal.
--
-- Two layers of protection on the target secret, both explicit:
--
--   1. **Storage layer** — the column-level grant on
--      `psychicnum.games` excludes target. Any direct SELECT
--      against the table by `authenticated` can't see target;
--      Postgres raises 42501 on the column. This is the
--      educational "true server-side secret" pattern.
--   2. **API layer** — this view's `target` expression calls a
--      SECURITY DEFINER helper (`_target_for`) that gates on
--      common.games.is_terminal. The view itself is
--      `security_invoker` so the row-visibility check still
--      goes through the table's RLS as the calling role.
--
-- Realtime: the view itself is NOT in the publication. The FE
-- subscribes to psychicnum.games for change events (winner_id,
-- guesses_remaining decrement) and refetches from this view in
-- response. Terminal transitions come through common.games via
-- useCommonGame.

-- Helper: returns the target value if and only if the game is
-- terminal. Otherwise null. SECURITY DEFINER means it runs as
-- the function owner (postgres), which has SELECT on the target
-- column (and on common.games.is_terminal) despite the
-- authenticated-role column grant exclusion. The "terminal-only"
-- gate reads from common.games.is_terminal — the single source
-- of truth for "did this game end?"
--
-- This is the only place authenticated callers can transitively
-- read `target`, and only via the games_state view that calls it.
-- A direct call to this function from the FE would also be gated
-- (terminal-only), but we revoke EXECUTE from public anyway —
-- the view is the intended call site.
create function psychicnum._target_for(g_id uuid)
returns int
language sql
stable
security definer
set search_path = psychicnum, common, public, extensions
as $$
  select case when c.is_terminal then p.target else null end
    from psychicnum.games p
    join common.games c on c.id = p.id
   where p.id = g_id
$$;

revoke execute on function psychicnum._target_for(uuid) from public;
-- Grant to authenticated so the view (which runs as the invoker
-- under security_invoker) can call it. The function's SECURITY
-- DEFINER property switches identity *inside* the call — that's
-- the bit that lets it read the target column.
grant execute on function psychicnum._target_for(uuid) to authenticated;

-- The view itself runs with the invoker's identity
-- (security_invoker = true). That's what makes RLS on the
-- underlying psychicnum.games apply to the calling user:
-- non-members see zero rows, just like a direct SELECT.
--
-- The trade for getting correct RLS: we can't put `target`
-- directly in the SELECT list, because the invoker doesn't have
-- SELECT on that column. The helper function above is the
-- workaround — it's SECURITY DEFINER, so the column access
-- inside the function uses postgres' identity.
create view psychicnum.games_state
  with (security_invoker = true)
as
  select
    id,
    club_id,
    guesses_remaining,
    winner_id,
    created_at,
    psychicnum._target_for(id) as target
  from psychicnum.games;

grant select on psychicnum.games_state to authenticated;
revoke insert, update, delete on psychicnum.games_state from authenticated;

-- ============================================================
-- Realtime publication
-- ============================================================
-- Both tables broadcast so the FE can subscribe to:
--   - games:    status flips (won/lost), guesses_remaining decrement
--   - guesses:  new entries (someone in your club guessed)

alter publication supabase_realtime add table psychicnum.games;
alter publication supabase_realtime add table psychicnum.guesses;

-- ============================================================
-- psychicnum.create_game(target_club, setup, player_user_ids)
-- ============================================================
-- Validates setup shape, then coordinates the two-write game-
-- creation (common-side then gametype-side):
--
--   1. common.create_game(target_club, 'psychicnum', player_user_ids,
--                          title, setup) — validates auth + caller
--      club-membership + every uid in player_user_ids is in
--      clubs_members, vacates any prior current-view game for
--      this club, inserts common.games (is_current_view=true,
--      play_state='playing', is_terminal=false) + one
--      common.game_players per uid, returns the canonical id.
--   2. INSERT INTO psychicnum.games using that id.
--
-- Setup shape:
--   { "guesses": 3 | 5 | 7 | 9,
--     "timer":   { "kind": "none" | "countup" }
--             |  { "kind": "countdown", "seconds": 1..3600 } }
--
-- Timer is browser-side (anchored to common.games.started_at,
-- ticked locally). When `countdown` hits 0 the FE fires
-- psychicnum.submit_timeout (below) and the game flips to 'lost'.
-- The `none` / `countup` modes have no server-side timeout
-- behavior at all — they're just FE display choices.
--
-- No member-count check — psychic-num plays with any club size.
-- Must agree with the `numberOfPlayers: [1, null]` declaration in
-- src/psychicnum/manifest.ts. See docs/code-conventions.md →
-- "Per-game player counts".

create function psychicnum.create_game(
  target_club uuid,
  setup jsonb,
  player_user_ids uuid[]
)
returns table(id uuid)
language plpgsql
security definer
set search_path = psychicnum, common, public, extensions
as $$
declare
  new_id uuid;
  s_guesses int;
  s_target int;
begin
  -- ─── Validate setup shape ────────────────────────────
  -- One option, four allowed values. We don't trust the FE for
  -- any of this — the dialog narrows TypeScript to the same set,
  -- but a curious client could send anything.
  --
  -- Missing-vs-bad-value split so each rejection has a clean
  -- message. Otherwise PL/pgSQL's % placeholder substitutes NULL
  -- as the empty string and we'd raise "...must be 3, 5, 7, or 9
  -- (got )" — readable, but confusingly empty in the parens.
  if (setup->>'guesses') is null then
    raise exception 'setup.guesses is required' using errcode = 'P0001';
  end if;
  s_guesses := (setup->>'guesses')::int;
  if s_guesses not in (3, 5, 7, 9) then
    raise exception 'setup.guesses must be 3, 5, 7, or 9 (got %)', s_guesses
      using errcode = 'P0001';
  end if;

  -- Timer is a per-game setup choice. Shape validation is shared
  -- across gametypes — see common.validate_timer for the exact
  -- message set ('setup.timer is required', 'kind must be ...',
  -- 'seconds must be 1..3600 (got X)', etc.).
  perform common.validate_timer(setup->'timer');

  -- Pick the random target now (instead of inline in the INSERT)
  -- so we can use it in the title. NOTE: this LEAKS the target
  -- via common.games.title — psychic-num is a toy game and the
  -- title carries no anti-cheat expectation. The column-level
  -- grant on psychicnum.games.target stays as the canonical
  -- "true server-side secret" example for future games (memory-
  -- pairing layouts, hidden Boggle boards) — see psychicnum.md.
  s_target := 1 + floor(random() * 10)::int;

  -- Common-side coordination: validates auth + caller membership +
  -- player_user_ids membership, inserts common.games (with title +
  -- setup) + game_players, returns the canonical id. Setup lives on
  -- common.games.setup — we pass it through verbatim now that it's
  -- shape-validated.
  --
  -- Saved-default arg: psychicnum's whole setup ({guesses, timer})
  -- is a per-club preference, so we save it verbatim. Next dialog
  -- open seeds with the same guesses-budget and timer the friends
  -- picked last time.
  new_id := common.create_game(
    target_club, 'psychicnum', player_user_ids,
    s_target::text,
    setup,
    setup
  );

  -- Insert the gametype-specific row using the canonical id.
  -- guesses_remaining seeds from s_guesses.
  insert into psychicnum.games (id, club_id, target, guesses_remaining)
  values (
    new_id,
    target_club,
    s_target,
    s_guesses
  );

  return query select new_id;
end;
$$;

revoke execute on function psychicnum.create_game(uuid, jsonb, uuid[]) from public;
grant execute on function psychicnum.create_game(uuid, jsonb, uuid[]) to authenticated;

-- ============================================================
-- psychicnum.submit_guess — the only mid-game action
-- ============================================================
-- Returns one of: 'correct' (caller won), 'wrong' (game
-- continues), 'lost' (caller's wrong guess used the last token).
--
-- Concurrency: the SELECT ... FOR UPDATE on the game row
-- serializes simultaneous calls. With "first correct guess wins"
-- semantics, if two players guess the target at the same instant,
-- whichever transaction commits first is the winner; the second
-- one sees status != 'active' and raises 'game is not active'.
--
-- Duplicate guesses are allowed — anyone can guess any number,
-- even one already-wrongly-guessed. A dumb move in a dumb game.
--
-- Terminal transitions call common.end_game directly (replacing
-- the per-gametype clear_active_on_termination trigger pattern) —
-- single-write-path for status_summary + per-player results +
-- club_active_game cleanup.

create function psychicnum.submit_guess(target_game uuid, guess int)
returns text
language plpgsql
security definer
set search_path = psychicnum, common, public, extensions
as $$
declare
  caller_id uuid;
  g psychicnum.games%rowtype;
  current_play_state text;
  -- Initial guess budget from common.games.setup. Used to compute
  -- `guesses_used` in the listing-label / end-game status jsonb.
  initial_guesses int;
  is_correct boolean;
  remaining int;
  player_results jsonb;
  -- The guesser's username, frozen into status on a win so the
  -- club-page listing can render "won — <name>" from the row
  -- alone (no follow-up profile fetch on the FE).
  winner_name text;
begin
  if guess is null or guess < 1 or guess > 10 then
    raise exception 'guess must be between 1 and 10' using errcode = 'P0001';
  end if;

  -- Lock the gametype row for serialization of concurrent
  -- submits. play_state lives on common.games now, read in a
  -- separate query below — the foo-lock guarantees that by the
  -- time we read play_state, any concurrent submit that ended
  -- the game has already committed.
  select * into g from psychicnum.games
   where psychicnum.games.id = target_game
   for update;
  if not found then
    raise exception 'game not found' using errcode = 'P0002';
  end if;

  -- Auth + game-player gate. See common.require_game_player —
  -- a club member who didn't sit down at this game can't guess.
  caller_id := common.require_game_player(target_game);

  -- Read play_state + initial guess budget from common.games.
  -- Cross-schema lookup against the foo-locked id is safe: the
  -- FOR UPDATE above serializes concurrent submits.
  select play_state, (setup->>'guesses')::int
    into current_play_state, initial_guesses
    from common.games where id = target_game;

  if current_play_state <> 'playing' then
    raise exception 'game is not active' using errcode = 'P0001';
  end if;

  is_correct := (guess = g.target);

  insert into psychicnum.guesses (game_id, user_id, number, was_correct)
  values (target_game, caller_id, guess, is_correct);

  if is_correct then
    update psychicnum.games
       set winner_id = caller_id,
           guesses_remaining = guesses_remaining - 1
     where psychicnum.games.id = target_game;

    -- Team win: everyone wins together (the spec is team-wins;
    -- the `winner_id` "who specifically guessed it" attribution
    -- is overspec, deferred for removal — see deferred.md).
    select jsonb_object_agg(user_id::text, '{"won": true}'::jsonb)
      into player_results
      from common.game_players
     where game_id = target_game;

    -- Resolve the guesser's username at end-of-game time. We
    -- freeze it into status so the club-page listing label
    -- ("won — bea guessed it") can be rendered from the row
    -- alone, with no follow-up profile fetch on the FE.
    -- Stale-on-rename is fine (renames are rare, and the
    -- frozen value reflects who-they-were-when-they-won, which
    -- is arguably the right thing to show).
    select username into winner_name
      from common.profiles where user_id = caller_id;

    -- common.end_game writes play_state='won', is_terminal=true,
    -- status (the listing-label jsonb), and per-player results.
    perform common.end_game(
      target_game,
      'won',
      jsonb_build_object(
        'outcome', 'won',
        -- initial budget minus the post-guess remaining count
        'guesses_used', initial_guesses - (g.guesses_remaining - 1),
        'winner_username', winner_name
      ),
      player_results
    );

    return 'correct';
  end if;

  remaining := g.guesses_remaining - 1;

  if remaining <= 0 then
    update psychicnum.games
       set guesses_remaining = 0
     where psychicnum.games.id = target_game;

    -- Team loss: everyone loses together.
    select jsonb_object_agg(user_id::text, '{"won": false}'::jsonb)
      into player_results
      from common.game_players
     where game_id = target_game;

    perform common.end_game(
      target_game,
      'lost',
      jsonb_build_object(
        'outcome', 'lost',
        'guesses_used', initial_guesses
      ),
      player_results
    );

    return 'lost';
  end if;

  -- Mid-game wrong guess. Update guesses_remaining on foo.games,
  -- mirror the listing-visible state into common.games via
  -- common.update_state (the duplicate-write discipline). play_state
  -- stays 'playing'.
  update psychicnum.games
     set guesses_remaining = remaining
   where psychicnum.games.id = target_game;

  perform common.update_state(
    target_game,
    'playing',
    jsonb_build_object('guesses_remaining', remaining)
  );

  return 'wrong';
end;
$$;

revoke execute on function psychicnum.submit_guess(uuid, int) from public;
grant execute on function psychicnum.submit_guess(uuid, int) to authenticated;

-- ============================================================
-- psychicnum.submit_timeout — countdown expired
-- ============================================================
-- The FE clock is browser-side (count-down ticks locally); when it
-- hits zero, the FE fires this. We flip the game to `lost` and call
-- common.end_game with an outcome of 'lost_timeout' to distinguish
-- it from the regular `lost` (exhausted guesses).
--
-- Idempotency: terminal-state guard via the `status <> 'active'`
-- check means a second concurrent call from another tab raises
-- P0001 'game is not active'. The FE swallows that — losing once
-- is enough.
--
-- Mirrors wordknit.submit_timeout exactly. See its header for the
-- pattern's rationale (FE-driven clock + idempotent server flip).

create function psychicnum.submit_timeout(target_game uuid)
returns void
language plpgsql
security definer
set search_path = psychicnum, common, public, extensions
as $$
declare
  g psychicnum.games%rowtype;
  current_play_state text;
  initial_guesses int;
  player_results jsonb;
begin
  -- Lock the gametype row; read play_state + initial guess budget
  -- from common.games separately.
  select * into g from psychicnum.games
   where psychicnum.games.id = target_game
   for update;
  if not found then
    raise exception 'game not found' using errcode = 'P0002';
  end if;

  -- Auth + game-player gate. See common.require_game_player.
  perform common.require_game_player(target_game);

  select play_state, (setup->>'guesses')::int
    into current_play_state, initial_guesses
    from common.games where id = target_game;

  if current_play_state <> 'playing' then
    raise exception 'game is not active' using errcode = 'P0001';
  end if;

  -- Team loss: everyone loses together.
  select jsonb_object_agg(user_id::text, '{"won": false}'::jsonb)
    into player_results
    from common.game_players
   where game_id = target_game;

  perform common.end_game(
    target_game,
    'lost',
    jsonb_build_object(
      'outcome', 'lost_timeout',
      -- How many guesses had been used before the clock ran out.
      'guesses_used', initial_guesses - g.guesses_remaining
    ),
    player_results
  );
end;
$$;

revoke execute on function psychicnum.submit_timeout(uuid) from public;
grant execute on function psychicnum.submit_timeout(uuid) to authenticated;

-- (The target-reveal flow is the games_state view above + the
-- _target_for helper. Single SELECT — no separate reveal RPC.)

-- ============================================================
-- Register psychicnum with common.gametypes
-- ============================================================

insert into common.gametypes (gametype) values ('psychicnum')
on conflict do nothing;
