-- ============================================================
-- psychicnum schema — baseline (squashed)
-- ============================================================
--
-- Psychic Num is a tiny cooperative number-guessing game: pick a
-- random target 1..10, hidden server-side; any club member can
-- guess at any time; first correct guess wins; running out of
-- guesses loses. Deliberately minimal — it exercises the
-- multi-game architecture (per-game schema, per-game theme,
-- per-game chunk split, column-level secrecy) with the absolute
-- minimum game-logic surface, so the patterns are legible
-- compared to tinyspy's richer shape.
--
-- What this exercises that tinyspy doesn't:
--   - N-player, no turns (anyone-acts-any-time)
--   - A genuine server-side secret (the target), hidden from the
--     client even with devtools open via a column-level grant
--     that excludes `target` from authenticated SELECT
--   - A different status enum (active/won/lost — no sudden_death,
--     no multi-axis loss reasons)
--
-- The static-starting-state vocabulary calls for a "boards" table
-- in some games (boggle's dice, crosswords' grid). Psychic Num's
-- only static datum is the target number — too small to warrant
-- its own table, so it co-locates onto the game row, matching how
-- tinyspy keeps its words alongside the game.
--
-- Depends on `common` (clubs, profiles, club_active_game,
-- is_club_member, gametypes). Per the removability invariant,
-- common MUST NOT reference psychicnum back.

-- ============================================================
-- Schema + usage grant
-- ============================================================

create schema if not exists psychicnum;
grant usage on schema psychicnum to authenticated;

-- ============================================================
-- psychicnum.games — one row per playing
-- ============================================================
-- `target` is the secret 1..10; column-grant excludes it from
-- authenticated SELECT (see grants below). RPCs run as the
-- postgres role under security definer and can read it freely;
-- the FE only learns it via the reveal_target RPC after the game
-- ends.
--
-- `setup jsonb` is the frozen-at-create-time player choices —
-- today just `{ "guesses": 3 | 5 | 7 | 9 }`. Persisted because the
-- mutable `guesses_remaining` counter decrements during play, so
-- after the game ends the counter at 0 doesn't tell you what the
-- starting budget was. The `setup` column preserves intent for
-- end-of-game review.
--
-- The `guesses_remaining between 0 and 9` constraint matches the
-- max allowed setup.guesses value.

-- psychicnum.games.id is FK'd to common.games(id) — the canonical
-- id is generated by common.create_game and passed in. ON DELETE
-- CASCADE means a row here goes away if its common.games parent
-- is deleted (e.g., the gametype is unregistered).
--
-- club_id stays on this row (denormalized from common.games.club_id)
-- so the RLS policy can ask is_club_member(club_id) without a join.

create table psychicnum.games (
  id uuid primary key references common.games(id) on delete cascade,
  club_id uuid not null references common.clubs(id) on delete cascade,
  status text not null default 'active'
    check (status in ('active', 'won', 'lost')),
  target int not null check (target between 1 and 10),
  guesses_remaining int not null default 7
    check (guesses_remaining between 0 and 9),
  winner_id uuid references common.profiles(user_id) on delete set null,
  setup jsonb not null,
  created_at timestamptz not null default now()
);

create index psychicnum_games_club_id_idx on psychicnum.games (club_id);

-- ============================================================
-- psychicnum.guesses — append-only log
-- ============================================================
-- Used both for "show the history" in the UI and for the
-- guesses_remaining counter (though we update the counter on
-- psychicnum.games inline rather than recomputing from this log,
-- to keep submit_guess cheap and to support a column-level RLS
-- story).

create table psychicnum.guesses (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references psychicnum.games(id) on delete cascade,
  user_id uuid not null references common.profiles(user_id) on delete cascade,
  number int not null check (number between 1 and 10),
  was_correct boolean not null,
  guessed_at timestamptz not null default now()
);

create index psychicnum_guesses_game_id_idx on psychicnum.guesses (game_id);

-- ============================================================
-- RLS
-- ============================================================
-- Club members can SELECT both tables. Writes never happen
-- directly — they go through the security-definer RPCs below.

alter table psychicnum.games enable row level security;
alter table psychicnum.guesses enable row level security;

-- A member of the club that owns this game can see the row.
-- (The `target` column is *additionally* hidden by a column-level
-- grant; see the grants section below.)
create policy games_select on psychicnum.games
  for select to authenticated
  using (common.is_club_member(club_id));

-- Guesses inherit visibility from their parent game.
create policy guesses_select on psychicnum.guesses
  for select to authenticated
  using (
    exists (
      select 1 from psychicnum.games g
       where g.id = guesses.game_id
         and common.is_club_member(g.club_id)
    )
  );

-- ============================================================
-- Grants — `target` is column-excluded
-- ============================================================
-- Default `grant select` would include `target`, defeating the
-- "backend-authoritative secret" property. Column-list grant
-- whitelists every column EXCEPT `target`. The RPCs run as the
-- postgres role (security definer) and can read `target`
-- freely; the authenticated role cannot.
--
-- After game termination, players reveal `target` via the
-- `reveal_target` RPC (see below), which gate-checks the
-- terminal-status precondition.

grant select
  (id, club_id, status, guesses_remaining, winner_id, setup, created_at)
  on psychicnum.games to authenticated;

grant select on psychicnum.guesses to authenticated;

-- ============================================================
-- Realtime publication
-- ============================================================
-- Both tables broadcast so the FE can subscribe to:
--   - games:    status flips (won/lost), guesses_remaining decrement
--   - guesses:  new entries (someone in your club guessed)

alter publication supabase_realtime add table psychicnum.games;
alter publication supabase_realtime add table psychicnum.guesses;

-- ============================================================
-- psychicnum.create_game(target_club, setup, player_user_ids)
-- ============================================================
-- Validates setup shape, then coordinates the two-write game-
-- creation (common-side then gametype-side):
--
--   1. common.create_game(target_club, 'psychicnum', player_user_ids)
--      — validates auth + caller club-membership + every uid in
--      player_user_ids is in clubs_members, clears any prior active
--      game for this club, inserts common.games (with is_active=true)
--      + one common.game_players per uid, returns the canonical id.
--   2. INSERT INTO psychicnum.games using that id.
--
-- Setup shape: { "guesses": 3 | 5 | 7 | 9 }
--
-- No member-count check — psychic-num plays with any club size.
-- Must agree with the `numberOfPlayers: [1, null]` declaration in
-- src/psychicnum/manifest.ts. See docs/code-conventions.md →
-- "Per-game player counts".

create function psychicnum.create_game(
  target_club uuid,
  setup jsonb,
  player_user_ids uuid[]
)
returns table(id uuid)
language plpgsql
security definer
set search_path = psychicnum, common, public, extensions
as $$
declare
  new_id uuid;
  s_guesses int;
begin
  -- ─── Validate setup shape ────────────────────────────
  -- One option, four allowed values. We don't trust the FE for
  -- any of this — the dialog narrows TypeScript to the same set,
  -- but a curious client could send anything.
  --
  -- Missing-vs-bad-value split so each rejection has a clean
  -- message. Otherwise PL/pgSQL's % placeholder substitutes NULL
  -- as the empty string and we'd raise "...must be 3, 5, 7, or 9
  -- (got )" — readable, but confusingly empty in the parens.
  if (setup->>'guesses') is null then
    raise exception 'setup.guesses is required' using errcode = 'P0001';
  end if;
  s_guesses := (setup->>'guesses')::int;
  if s_guesses not in (3, 5, 7, 9) then
    raise exception 'setup.guesses must be 3, 5, 7, or 9 (got %)', s_guesses
      using errcode = 'P0001';
  end if;

  -- Common-side coordination: validates auth + caller membership +
  -- player_user_ids membership, inserts common.games + game_players,
  -- returns the canonical id.
  new_id := common.create_game(target_club, 'psychicnum', player_user_ids);

  -- Insert the game row using the canonical id. guesses_remaining
  -- seeds from s_guesses; setup itself is persisted for game-
  -- review surfaces. target is the random 1..10 secret, hidden by
  -- the column-level grant.
  insert into psychicnum.games (id, club_id, target, guesses_remaining, setup)
  values (
    new_id,
    target_club,
    1 + floor(random() * 10)::int,
    s_guesses,
    setup
  );

  return query select new_id;
end;
$$;

revoke execute on function psychicnum.create_game(uuid, jsonb, uuid[]) from public;
grant execute on function psychicnum.create_game(uuid, jsonb, uuid[]) to authenticated;

-- ============================================================
-- psychicnum.submit_guess — the only mid-game action
-- ============================================================
-- Returns one of: 'correct' (caller won), 'wrong' (game
-- continues), 'lost' (caller's wrong guess used the last token).
--
-- Concurrency: the SELECT ... FOR UPDATE on the game row
-- serializes simultaneous calls. With "first correct guess wins"
-- semantics, if two players guess the target at the same instant,
-- whichever transaction commits first is the winner; the second
-- one sees status != 'active' and raises 'game is not active'.
--
-- Duplicate guesses are allowed — anyone can guess any number,
-- even one already-wrongly-guessed. A dumb move in a dumb game.
--
-- Terminal transitions call common.end_game directly (replacing
-- the per-gametype clear_active_on_termination trigger pattern) —
-- single-write-path for status_summary + per-player results +
-- club_active_game cleanup.

create function psychicnum.submit_guess(target_game uuid, guess int)
returns text
language plpgsql
security definer
set search_path = psychicnum, common, public, extensions
as $$
declare
  caller_id uuid;
  g psychicnum.games%rowtype;
  is_correct boolean;
  remaining int;
  player_results jsonb;
begin
  if guess is null or guess < 1 or guess > 10 then
    raise exception 'guess must be between 1 and 10' using errcode = 'P0001';
  end if;

  select * into g from psychicnum.games
   where psychicnum.games.id = target_game
   for update;
  if not found then
    raise exception 'game not found' using errcode = 'P0002';
  end if;

  -- Auth + game-player gate. See common.require_game_player —
  -- a club member who didn't sit down at this game can't guess.
  caller_id := common.require_game_player(target_game);

  if g.status <> 'active' then
    raise exception 'game is not active' using errcode = 'P0001';
  end if;

  is_correct := (guess = g.target);

  insert into psychicnum.guesses (game_id, user_id, number, was_correct)
  values (target_game, caller_id, guess, is_correct);

  if is_correct then
    update psychicnum.games
       set status = 'won',
           winner_id = caller_id,
           guesses_remaining = guesses_remaining - 1
     where psychicnum.games.id = target_game;

    -- Team win: everyone wins together (the spec is team-wins;
    -- the `winner_id` "who specifically guessed it" attribution
    -- is overspec, deferred for removal — see deferred.md).
    select jsonb_object_agg(user_id::text, '{"won": true}'::jsonb)
      into player_results
      from common.game_players
     where game_id = target_game;

    perform common.end_game(
      target_game,
      jsonb_build_object(
        'outcome', 'won',
        -- initial budget minus the post-guess remaining count
        'guesses_used',
          (g.setup->>'guesses')::int - (g.guesses_remaining - 1)
      ),
      player_results
    );

    return 'correct';
  end if;

  remaining := g.guesses_remaining - 1;

  if remaining <= 0 then
    update psychicnum.games
       set status = 'lost',
           guesses_remaining = 0
     where psychicnum.games.id = target_game;

    -- Team loss: everyone loses together.
    select jsonb_object_agg(user_id::text, '{"won": false}'::jsonb)
      into player_results
      from common.game_players
     where game_id = target_game;

    perform common.end_game(
      target_game,
      jsonb_build_object(
        'outcome', 'lost',
        'guesses_used', (g.setup->>'guesses')::int
      ),
      player_results
    );

    return 'lost';
  end if;

  update psychicnum.games
     set guesses_remaining = remaining
   where psychicnum.games.id = target_game;
  return 'wrong';
end;
$$;

revoke execute on function psychicnum.submit_guess(uuid, int) from public;
grant execute on function psychicnum.submit_guess(uuid, int) to authenticated;

-- ============================================================
-- psychicnum.reveal_target — surfaces the secret after game end
-- ============================================================
-- The `target` column is hidden from authenticated SELECT via
-- column-level grant (see the grants section). Players need to
-- see the number after a loss ("the number was 7"); this RPC is
-- the gated path. Rejects while the game is still active so a
-- curious client can't peek mid-game.

create function psychicnum.reveal_target(target_game uuid)
returns int
language plpgsql
security definer
set search_path = psychicnum, common, public, extensions
as $$
declare
  g psychicnum.games%rowtype;
begin
  select * into g from psychicnum.games
   where psychicnum.games.id = target_game;
  if not found then
    raise exception 'game not found' using errcode = 'P0002';
  end if;

  -- Auth + membership (deferred to after the lookup so we can use
  -- the game row's club_id). See common.require_club_member.
  perform common.require_club_member(g.club_id);

  if g.status = 'active' then
    raise exception 'game is still active' using errcode = 'P0001';
  end if;

  return g.target;
end;
$$;

revoke execute on function psychicnum.reveal_target(uuid) from public;
grant execute on function psychicnum.reveal_target(uuid) to authenticated;

-- ============================================================
-- Register psychicnum with common.gametypes
-- ============================================================

insert into common.gametypes (gametype) values ('psychicnum')
on conflict do nothing;
